// apps/web/src/pages/settings/browser.tsx
import { useQuery } from "@tanstack/react-query";
import { clamp } from "lodash-es";
import {
  ArrowUpCircle,
  CheckCircle,
  Download,
  FileCog,
  FolderOpen,
  Info,
  RefreshCw,
  Save,
  Trash2,
  X,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";

import { ACTIVE_STATUSES } from "#shared/model/settings";
import type { DownloadState, DownloadStatus } from "#shared/model/settings";
import { LoadingState } from "@/components/common/loading-state";
import {
  SettingsBlock,
  SettingsSection,
} from "@/components/common/settings-section";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { toast } from "@/components/ui/sonner";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useDownloadStream } from "@/hooks/use-download-stream";
import { BrowserData } from "@/lib/api";
import { errorMessage } from "@/lib/http";

const IDLE_STATE: DownloadState = {
  buildId: null,
  downloadedBytes: 0,
  platform: null,
  status: "idle",
  totalBytes: 0,
};

const toMB = (b: number): string => (b / 1024 / 1024).toFixed(1);

interface UpdateInfo {
  currentBuildId: string | null;
  hasUpdate: boolean;
  latestBuildId: string;
}

const UpdateInfoAlert = ({ info }: { info: UpdateInfo }) => {
  if (!info.hasUpdate) {
    return (
      <Alert variant="info">
        <CheckCircle />
        <AlertDescription>
          已是最新版本 <strong>{info.latestBuildId}</strong>
        </AlertDescription>
      </Alert>
    );
  }
  return (
    <Alert variant="warning">
      <ArrowUpCircle />
      <AlertDescription>
        <div className="flex flex-col gap-1 text-sm">
          <span>
            发现新版本 <strong>{info.latestBuildId}</strong>
          </span>
          {info.currentBuildId ? (
            <span className="text-muted-foreground text-xs">
              当前版本：{info.currentBuildId}
            </span>
          ) : null}
        </div>
      </AlertDescription>
    </Alert>
  );
};

// 内容较多但均为展示逻辑，复杂度上限对此类页面过严。
// oxlint-disable-next-line eslint/complexity
export const BrowserContent = () => {
  const [mode, setMode] = useState<"download" | "custom">("download");
  const [downloadState, setDownloadState] = useState<DownloadState>(IDLE_STATE);
  const [customPath, setCustomPath] = useState("");
  const [savingPath, setSavingPath] = useState(false);
  const [startingDownload, setStartingDownload] = useState(false);
  const [checkingUpdate, setCheckingUpdate] = useState(false);
  const [updateInfo, setUpdateInfo] = useState<UpdateInfo | null>(null);

  const {
    data: config,
    isLoading: configLoading,
    refetch: refetchConfig,
  } = useQuery({
    queryFn: async () => BrowserData.get(),
    queryKey: ["browser-config"],
  });

  const isDownloading = ACTIVE_STATUSES.has(downloadState.status);
  const downloadProgress = downloadState.totalBytes
    ? clamp(
        Math.round(
          (downloadState.downloadedBytes / downloadState.totalBytes) * 100,
        ),
        0,
        100,
      )
    : 0;

  // 进度状态切换提示（active → done/error）。
  const prevStatus = useRef<DownloadStatus>("idle");
  useEffect(() => {
    const wasActive = ACTIVE_STATUSES.has(prevStatus.current);
    prevStatus.current = downloadState.status;
    if (!wasActive) {
      return;
    }
    if (downloadState.status === "done") {
      toast.success("Chrome Headless Shell 下载完成", {
        description: `已安装到：${downloadState.executablePath ?? ""}`,
      });
      void refetchConfig();
    } else if (downloadState.status === "error") {
      toast.error("下载失败", { description: downloadState.error });
    }
  }, [downloadState, refetchConfig]);

  useDownloadStream(true, setDownloadState);

  const downloadStatusText = ((): string => {
    const { status, downloadedBytes, totalBytes } = downloadState;
    if (status === "downloading") {
      return totalBytes > 0
        ? `下载中 ${toMB(downloadedBytes)} / ${toMB(totalBytes)} MB (${downloadProgress}%)`
        : "下载中...";
    }
    if (status === "error") {
      return `下载失败：${downloadState.error ?? "未知错误"}`;
    }
    const map: Partial<Record<DownloadStatus, string>> = {
      done: "下载完成！",
      idle: "等待下载",
      resolving: "正在获取最新版本信息...",
      unpacking: "正在解压安装...",
    };
    return map[status] ?? "";
  })();

  const showProgress =
    isDownloading ||
    downloadState.status === "done" ||
    downloadState.status === "error";

  const startDownload = async (): Promise<void> => {
    setStartingDownload(true);
    try {
      await BrowserData.startDownload();
      setDownloadState({ ...IDLE_STATE, status: "resolving" });
    } catch (error) {
      toast.error("启动下载失败", { description: errorMessage(error) });
    } finally {
      setStartingDownload(false);
    }
  };

  const cancelDownload = async (): Promise<void> => {
    try {
      await BrowserData.cancelDownload();
      setDownloadState(IDLE_STATE);
      toast("下载已取消");
    } catch {
      toast.error("取消失败");
    }
  };

  const saveCustomPath = async (): Promise<void> => {
    if (!customPath.trim()) {
      toast.warning("请输入浏览器可执行文件路径");
      return;
    }
    setSavingPath(true);
    try {
      await BrowserData.patch(customPath.trim());
      toast.success("浏览器路径已保存");
      await refetchConfig();
    } catch (error) {
      toast.error("保存失败", { description: errorMessage(error) });
    } finally {
      setSavingPath(false);
    }
  };

  const clearPath = async (): Promise<void> => {
    setSavingPath(true);
    try {
      await BrowserData.patch(null);
      setCustomPath("");
      toast.success("已清除自定义路径，将使用自动检测");
      await refetchConfig();
    } catch {
      toast.error("操作失败");
    } finally {
      setSavingPath(false);
    }
  };

  const checkUpdate = async (): Promise<void> => {
    setCheckingUpdate(true);
    try {
      setUpdateInfo((await BrowserData.checkUpdate()) ?? null);
    } catch {
      toast.error("检查更新失败");
    } finally {
      setCheckingUpdate(false);
    }
  };

  return (
    <>
      {configLoading ? (
        <LoadingState />
      ) : (
        <div className="flex flex-col gap-8">
          <SettingsSection
            description="图片渲染功能需要浏览器支持（chrome-headless-shell）"
            title={
              <span className="inline-flex items-center gap-2">
                浏览器
                {config?.executablePath ? (
                  <Badge variant="success">已配置</Badge>
                ) : (
                  <Badge variant="warning">未配置</Badge>
                )}
              </span>
            }
          >
            {config?.executablePath ? (
              <SettingsBlock>
                <div className="bg-muted/30 flex items-start gap-2 overflow-hidden rounded-md px-3 py-2 font-mono text-sm">
                  <FileCog className="text-muted-foreground mt-0.5 size-4 shrink-0" />
                  <span className="text-muted-foreground min-w-0 break-all">
                    {config.executablePath}
                  </span>
                </div>
              </SettingsBlock>
            ) : (
              <SettingsBlock>
                <Alert variant="info">
                  <Info />
                  <AlertDescription>
                    未设置自定义路径。系统将自动检测已下载的
                    Chromium，或你可以在下方下载/设置。
                  </AlertDescription>
                </Alert>
              </SettingsBlock>
            )}
          </SettingsSection>

          <Tabs
            onValueChange={(v) => {
              setMode(v as "custom" | "download");
            }}
            value={mode}
          >
            <TabsList className="w-full">
              <TabsTrigger value="download">
                <Download className="size-4" />
                自动下载
              </TabsTrigger>
              <TabsTrigger value="custom">
                <FolderOpen className="size-4" />
                手动指定路径
              </TabsTrigger>
            </TabsList>
          </Tabs>

          {mode === "download" ? (
            <SettingsSection
              description="自动下载适合当前系统的 Chrome Headless Shell，并保存至 ./data/browsers/"
              title="下载 Chrome Headless Shell"
            >
              <SettingsBlock>
                <div className="flex flex-col gap-4">
                  {showProgress ? (
                    <div className="flex flex-col gap-2">
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-muted-foreground">
                          {downloadStatusText}
                        </span>
                        {downloadState.status === "downloading" &&
                        downloadState.totalBytes > 0 ? (
                          <span className="text-muted-foreground font-mono text-xs">
                            {downloadProgress}%
                          </span>
                        ) : null}
                      </div>
                      <Progress
                        value={
                          downloadState.status === "unpacking"
                            ? undefined
                            : downloadProgress
                        }
                      />
                      {downloadState.buildId ? (
                        <div className="text-muted-foreground flex gap-4 text-xs">
                          <span>版本：{downloadState.buildId}</span>
                          <span>平台：{downloadState.platform}</span>
                        </div>
                      ) : null}
                    </div>
                  ) : (
                    <p className="text-muted-foreground text-sm">
                      将自动选择适合当前系统的版本下载并安装，速度取决于网络环境。
                    </p>
                  )}

                  <div className="flex flex-wrap gap-2">
                    {isDownloading ? (
                      <Button
                        onClick={() => {
                          void cancelDownload();
                        }}
                        variant="destructive"
                      >
                        <X />
                        取消
                      </Button>
                    ) : (
                      <Button
                        disabled={startingDownload}
                        onClick={() => {
                          void startDownload();
                        }}
                      >
                        <Download />
                        {downloadState.executablePath === undefined
                          ? "开始下载"
                          : "重新下载"}
                      </Button>
                    )}
                    <Button
                      disabled={isDownloading || checkingUpdate}
                      onClick={() => {
                        void checkUpdate();
                      }}
                      variant="secondary"
                    >
                      <RefreshCw />
                      检查更新
                    </Button>
                  </div>

                  {updateInfo ? <UpdateInfoAlert info={updateInfo} /> : null}
                </div>
              </SettingsBlock>
            </SettingsSection>
          ) : (
            <SettingsSection
              description="填写系统中已安装的 Chrome Headless Shell 或 Chromium 可执行文件的绝对路径"
              title="手动指定浏览器路径"
            >
              <SettingsBlock>
                <div className="flex flex-col gap-4">
                  <div className="space-y-1.5">
                    <Label htmlFor="customPath">可执行文件路径</Label>
                    <Input
                      id="customPath"
                      onChange={(e) => {
                        setCustomPath(e.target.value);
                      }}
                      placeholder="例如：/usr/bin/chrome-headless-shell"
                      value={customPath}
                    />
                  </div>
                  <div className="flex gap-2">
                    <Button
                      disabled={savingPath}
                      onClick={() => {
                        void saveCustomPath();
                      }}
                    >
                      <Save />
                      保存路径
                    </Button>
                    {config?.executablePath ? (
                      <Button
                        disabled={savingPath}
                        onClick={() => {
                          void clearPath();
                        }}
                        variant="destructive"
                      >
                        <Trash2 />
                        清除
                      </Button>
                    ) : null}
                  </div>
                </div>
              </SettingsBlock>
            </SettingsSection>
          )}
        </div>
      )}
    </>
  );
};

// app/pages/settings/browser.vue
<script lang="ts" setup>
import { clamp } from "lodash-es";
import { FetchError } from "ofetch";
import type {
  DownloadState,
  DownloadStatus,
} from "~~/server/service/browser-downloader";

import { BrowserData } from "@/composables/api";

// ─── 常量 ───────────────────────────────────────────────────────────────────

const ACTIVE_STATUSES = new Set<DownloadStatus>([
  "resolving",
  "downloading",
  "unpacking",
]);

const IDLE_STATE: DownloadState = {
  buildId: null,
  downloadedBytes: 0,
  platform: null,
  status: "idle",
  totalBytes: 0,
};

const toMB = (b: number) => (b / 1024 / 1024).toFixed(1);

interface FetchErrorData {
  message?: string;
}

const fetchErrorMsg = (error: unknown): string => {
  if (error instanceof FetchError) {
    const data = error.data as FetchErrorData | null;
    return data?.message ?? error.message;
  }
  return String(error);
};

// ─── 类型 ───────────────────────────────────────────────────────────────────

interface UpdateInfo {
  currentBuildId: string | null;
  hasUpdate: boolean;
  latestBuildId: string;
}

type Mode = "download" | "custom";

// ─── 状态 ────────────────────────────────────────────────────────────────────

const toast = useToast();
const mode = ref<Mode>("download");
const isLoading = ref(false);
const isInitializing = ref(true);
const currentConfig = ref<{ executablePath: string | null }>({
  executablePath: null,
});
const customPath = ref("");
const isSavingPath = ref(false);
const downloadState = ref<DownloadState>({ ...IDLE_STATE });
const isStartingDownload = ref(false);
const updateInfo = ref<UpdateInfo | null>(null);
const isCheckingUpdate = ref(false);

let progressSource: EventSource | null = null;

// ─── 计算属性 ─────────────────────────────────────────────────────────────────

const isDownloading = computed(() =>
  ACTIVE_STATUSES.has(downloadState.value.status),
);

const downloadProgress = computed(() => {
  const { downloadedBytes, totalBytes } = downloadState.value;
  if (!totalBytes) {
    return 0;
  }
  return clamp(Math.round((downloadedBytes / totalBytes) * 100), 0, 100);
});

const downloadProgressColor = computed<
  "primary" | "success" | "error" | "warning" | "neutral"
>(() => {
  const { status } = downloadState.value;
  if (status === "done") {
    return "success";
  }
  if (status === "error") {
    return "error";
  }
  return "primary";
});

const downloadStatusText = computed(() => {
  const { status, downloadedBytes, totalBytes } = downloadState.value;
  if (status === "downloading") {
    return totalBytes > 0
      ? `下载中 ${toMB(downloadedBytes)} / ${toMB(totalBytes)} MB (${downloadProgress.value}%)`
      : "下载中...";
  }
  if (status === "error") {
    return `下载失败：${downloadState.value.error ?? "未知错误"}`;
  }
  const statusMap: Partial<Record<DownloadStatus, string>> = {
    done: "下载完成！",
    idle: "等待下载",
    resolving: "正在获取最新版本信息...",
    unpacking: "正在解压安装...",
  };
  return statusMap[status] ?? "";
});

const showProgressSection = computed(
  () =>
    isDownloading.value ||
    downloadState.value.status === "done" ||
    downloadState.value.status === "error",
);

// ─── 方法 ─────────────────────────────────────────────────────────────────────

const stopProgressStream = () => {
  progressSource?.close();
  progressSource = null;
};

const loadConfig = async () => {
  isLoading.value = true;
  try {
    const data = await BrowserData.get();
    currentConfig.value = data ?? { executablePath: null };
  } catch {
    toast.add({ color: "error", title: "加载配置失败" });
  } finally {
    isLoading.value = false;
  }
};

const startProgressStream = () => {
  stopProgressStream();
  progressSource = new EventSource("/api/settings/browser/download-stream");

  progressSource.addEventListener("progress", (event) => {
    if (!(event instanceof MessageEvent)) {
      return;
    }
    try {
      const payload = JSON.parse(event.data) as DownloadState;
      downloadState.value = payload;
    } catch {
      // ignore
    }
  });

  progressSource.addEventListener("error", () => {
    stopProgressStream();
    if (isDownloading.value) {
      setTimeout(startProgressStream, 1500);
    }
  });
};

watch(downloadState, (state, prevState) => {
  const wasActive = ACTIVE_STATUSES.has(prevState.status);
  if (!wasActive) {
    return;
  }

  if (state.status === "done") {
    toast.add({
      color: "success",
      description: `已安装到：${state.executablePath ?? ""}`,
      title: "Chrome Headless Shell 下载完成",
    });
    void loadConfig();
  } else if (state.status === "error") {
    toast.add({
      color: "error",
      description: state.error,
      title: "下载失败",
    });
  }
});

const startDownload = async () => {
  isStartingDownload.value = true;
  try {
    await BrowserData.startDownload();
    downloadState.value = { ...IDLE_STATE, status: "resolving" };
    startProgressStream();
  } catch (error) {
    toast.add({
      color: "error",
      description: fetchErrorMsg(error),
      title: "启动下载失败",
    });
  } finally {
    isStartingDownload.value = false;
  }
};

const cancelDownload = async () => {
  try {
    await BrowserData.cancelDownload();
    downloadState.value = { ...IDLE_STATE };
    toast.add({ color: "neutral", title: "下载已取消" });
  } catch {
    toast.add({ color: "error", title: "取消失败" });
  }
};

const saveCustomPath = async () => {
  if (!customPath.value.trim()) {
    toast.add({ color: "warning", title: "请输入浏览器可执行文件路径" });
    return;
  }
  isSavingPath.value = true;
  try {
    await BrowserData.patch(customPath.value.trim());
    toast.add({ color: "success", title: "浏览器路径已保存" });
    await loadConfig();
  } catch (error) {
    toast.add({
      color: "error",
      description: fetchErrorMsg(error),
      title: "保存失败",
    });
  } finally {
    isSavingPath.value = false;
  }
};

const clearPath = async () => {
  isSavingPath.value = true;
  try {
    await BrowserData.patch(null);
    customPath.value = "";
    toast.add({ color: "success", title: "已清除自定义路径，将使用自动检测" });
    await loadConfig();
  } catch {
    toast.add({ color: "error", title: "操作失败" });
  } finally {
    isSavingPath.value = false;
  }
};

const checkUpdate = async () => {
  isCheckingUpdate.value = true;
  try {
    updateInfo.value = (await BrowserData.checkUpdate()) ?? null;
  } catch {
    toast.add({ color: "error", title: "检查更新失败" });
  } finally {
    isCheckingUpdate.value = false;
  }
};

// ─── 生命周期 ─────────────────────────────────────────────────────────────────

onMounted(async () => {
  try {
    await loadConfig();
    startProgressStream();
  } catch {
    // ignore
  } finally {
    isInitializing.value = false;
  }
});

onUnmounted(() => {
  stopProgressStream();
});
</script>

<template>
  <div class="flex flex-col gap-4">
    <LoadingState v-if="isInitializing" />
    <template v-else>
      <!-- 当前状态 -->
      <UPageCard icon="i-lucide-chrome" title="浏览器" variant="outline">
        <template #description>
          <span
            class="text-muted inline-flex flex-wrap items-center gap-1.5 text-sm"
          >
            图片渲染功能需要浏览器支持（chrome-headless-shell）。当前状态：
            <UBadge
              v-if="currentConfig.executablePath"
              color="success"
              variant="subtle"
            >
              已配置
            </UBadge>
            <UBadge v-else color="warning" variant="subtle"> 未配置 </UBadge>
          </span>
        </template>
        <template #footer>
          <div class="flex w-full flex-col gap-2">
            <div
              v-if="currentConfig.executablePath"
              class="bg-muted/30 flex items-start gap-2 overflow-hidden rounded-md px-3 py-2 font-mono text-sm"
            >
              <UIcon
                name="i-lucide-file-cog"
                class="text-muted mt-0.5 shrink-0"
              />
              <span class="text-muted min-w-0 break-all">{{
                currentConfig.executablePath
              }}</span>
            </div>
            <UAlert
              v-else
              color="info"
              variant="subtle"
              icon="i-lucide-info"
              description="未设置自定义路径。系统将自动检测已下载的 Chromium，或你可以在下方下载/设置。"
            />
          </div>
        </template>
      </UPageCard>

      <!-- 模式选择 -->
      <UTabs
        v-model="mode"
        :items="[
          { label: '自动下载', value: 'download', icon: 'i-lucide-download' },
          {
            label: '手动指定路径',
            value: 'custom',
            icon: 'i-lucide-folder-open',
          },
        ]"
      />

      <!-- 下载模式 -->
      <template v-if="mode === 'download'">
        <UPageCard
          icon="i-lucide-download-cloud"
          title="下载 Chrome Headless Shell"
          variant="outline"
        >
          <template #description>
            <span class="text-muted text-sm">
              自动下载适合当前系统的 Chrome Headless Shell，并保存至
              <code class="bg-muted/50 rounded px-1 text-xs"
                >./data/browsers/</code
              >
              。检测到已安装时可重新下载以获取最新版本。
            </span>
          </template>

          <template #footer>
            <div class="flex w-full flex-col gap-4">
              <!-- 进度区 -->
              <template v-if="showProgressSection">
                <div class="flex flex-col gap-2">
                  <div class="flex items-center justify-between text-sm">
                    <span class="text-muted">{{ downloadStatusText }}</span>
                    <span
                      v-if="
                        downloadState.status === 'downloading' &&
                        downloadState.totalBytes > 0
                      "
                      class="text-muted font-mono text-xs"
                    >
                      {{ downloadProgress }}%
                    </span>
                  </div>
                  <UProgress
                    :model-value="
                      downloadState.status === 'unpacking'
                        ? null
                        : downloadProgress
                    "
                    :color="downloadProgressColor"
                    size="sm"
                    :animation="
                      downloadState.status === 'unpacking'
                        ? 'carousel'
                        : undefined
                    "
                  />
                  <div
                    v-if="downloadState.buildId"
                    class="text-muted flex gap-4 text-xs"
                  >
                    <span>版本：{{ downloadState.buildId }}</span>
                    <span>平台：{{ downloadState.platform }}</span>
                  </div>
                </div>
              </template>

              <template v-else>
                <div class="text-muted text-sm">
                  将自动选择适合当前系统的版本下载并安装，速度取决于网络环境。
                </div>
              </template>

              <!-- 按钮组 -->
              <div class="flex flex-wrap gap-2">
                <UButton
                  v-if="!isDownloading"
                  icon="i-lucide-download"
                  :loading="isStartingDownload"
                  @click="startDownload"
                >
                  {{
                    downloadState.executablePath !== undefined
                      ? "重新下载"
                      : "开始下载"
                  }}
                </UButton>
                <UButton
                  v-if="isDownloading"
                  color="error"
                  variant="subtle"
                  icon="i-lucide-x"
                  @click="cancelDownload"
                >
                  取消
                </UButton>
                <UButton
                  color="neutral"
                  variant="subtle"
                  icon="i-lucide-refresh-cw"
                  :disabled="isDownloading"
                  :loading="isCheckingUpdate"
                  @click="checkUpdate"
                >
                  检查更新
                </UButton>
              </div>

              <!-- 更新信息 -->
              <template v-if="updateInfo">
                <UAlert
                  v-if="updateInfo.hasUpdate"
                  color="warning"
                  variant="subtle"
                  icon="i-lucide-arrow-up-circle"
                >
                  <template #description>
                    <div class="flex flex-col gap-1 text-sm">
                      <span
                        >发现新版本
                        <strong>{{ updateInfo.latestBuildId }}</strong></span
                      >
                      <span
                        v-if="updateInfo.currentBuildId"
                        class="text-muted text-xs"
                      >
                        当前版本：{{ updateInfo.currentBuildId }}
                      </span>
                    </div>
                  </template>
                </UAlert>
                <UAlert
                  v-else
                  color="success"
                  variant="subtle"
                  icon="i-lucide-check-circle"
                >
                  <template #description>
                    <span class="text-sm">
                      已是最新版本
                      <strong>{{ updateInfo.latestBuildId }}</strong>
                    </span>
                  </template>
                </UAlert>
              </template>
            </div>
          </template>
        </UPageCard>
      </template>

      <!-- 自定义路径模式 -->
      <template v-if="mode === 'custom'">
        <UPageCard
          icon="i-lucide-folder-open"
          title="手动指定浏览器路径"
          variant="outline"
        >
          <template #description>
            <span class="text-muted text-sm">
              填写系统中已安装的 Chrome Headless Shell 或 Chromium
              可执行文件的绝对路径。
            </span>
          </template>
          <template #footer>
            <div class="flex w-full flex-col gap-4">
              <UFormField label="可执行文件路径">
                <div class="flex w-full gap-2">
                  <UInput
                    v-model="customPath"
                    placeholder="例如：/usr/bin/chrome-headless-shell"
                    class="flex-1"
                    icon="i-lucide-file-cog"
                  />
                </div>
              </UFormField>
              <div class="flex gap-2">
                <UButton
                  icon="i-lucide-save"
                  :loading="isSavingPath"
                  @click="saveCustomPath"
                >
                  保存路径
                </UButton>
                <UButton
                  v-if="currentConfig.executablePath"
                  color="error"
                  variant="subtle"
                  icon="i-lucide-trash-2"
                  :loading="isSavingPath"
                  @click="clearPath"
                >
                  清除
                </UButton>
              </div>
            </div>
          </template>
        </UPageCard>
      </template>
    </template>
  </div>
</template>
