// apps/web/src/components/target/transfer-list.tsx
import {
  ArrowLeftRight,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  Inbox,
  List,
  WifiOff,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

export interface TransferItem {
  value: string;
  label: string;
  description?: string;
  avatar?: string;
}

const Listbox = ({
  items,
  picked,
  onPicked,
  loading,
  emptyIcon,
  emptyText,
}: {
  items: TransferItem[];
  picked: string[];
  onPicked: (next: string[]) => void;
  loading: boolean;
  emptyIcon: React.ReactNode;
  emptyText: string;
}) => {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => {
    const q = query.toLowerCase();
    return items.filter(
      (i) =>
        i.label.toLowerCase().includes(q) ||
        (i.description ?? "").toLowerCase().includes(q),
    );
  }, [items, query]);

  const toggle = (value: string): void => {
    onPicked(
      picked.includes(value)
        ? picked.filter((v) => v !== value)
        : [...picked, value],
    );
  };

  return (
    <div className="flex min-h-0 flex-1 flex-col">
      <div className="p-2">
        <Input
          onChange={(e) => {
            setQuery(e.target.value);
          }}
          placeholder="搜索..."
          value={query}
        />
      </div>
      <div className="scrollbar-custom min-h-0 flex-1 overflow-y-auto px-1 pb-1">
        {filtered.length === 0 ? (
          <div className="flex flex-col items-center gap-2 py-10 text-center">
            {loading ? null : emptyIcon}
            <span className="text-muted-foreground text-sm">
              {loading ? "加载中..." : emptyText}
            </span>
          </div>
        ) : (
          filtered.map((item) => (
            <button
              className={cn(
                "hover:bg-accent flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left transition-colors",
                picked.includes(item.value) && "bg-accent",
              )}
              key={item.value}
              onClick={() => {
                toggle(item.value);
              }}
              type="button"
            >
              <Avatar className="size-7">
                {item.avatar ? <AvatarImage src={item.avatar} /> : null}
                <AvatarFallback>{item.label.slice(0, 1)}</AvatarFallback>
              </Avatar>
              <div className="min-w-0 flex-1">
                <div className="truncate text-sm font-medium">{item.label}</div>
                {item.description ? (
                  <div className="text-muted-foreground truncate text-xs">
                    {item.description}
                  </div>
                ) : null}
              </div>
            </button>
          ))
        )}
      </div>
    </div>
  );
};

/** 双列穿梭框。 */
export const TransferList = ({
  items,
  selected,
  onChange,
  loading,
  error,
  onReload,
}: {
  items: TransferItem[];
  selected: Set<string>;
  onChange: (next: Set<string>) => void;
  loading: boolean;
  error: string | null;
  onReload: () => void;
}) => {
  const [availablePicked, setAvailablePicked] = useState<string[]>([]);
  const [selectedPicked, setSelectedPicked] = useState<string[]>([]);

  const selectedItems = items.filter((i) => selected.has(i.value));
  const availableItems = items.filter((i) => !selected.has(i.value));

  // 用稳定的字符串键作依赖，并在无变化时返回同一引用，避免无限重渲染。
  const availableKey = availableItems.map((i) => i.value).join("|");
  const selectedKey = selectedItems.map((i) => i.value).join("|");

  useEffect(() => {
    const valid = new Set(availableKey ? availableKey.split("|") : []);
    setAvailablePicked((p) => {
      const next = p.filter((v) => valid.has(v));
      return next.length === p.length ? p : next;
    });
  }, [availableKey]);
  useEffect(() => {
    const valid = new Set(selectedKey ? selectedKey.split("|") : []);
    setSelectedPicked((p) => {
      const next = p.filter((v) => valid.has(v));
      return next.length === p.length ? p : next;
    });
  }, [selectedKey]);

  const addPicked = (): void => {
    const next = new Set(selected);
    for (const v of availablePicked) {
      next.add(v);
    }
    onChange(next);
    setAvailablePicked([]);
  };

  const removePicked = (): void => {
    const next = new Set(selected);
    for (const v of selectedPicked) {
      next.delete(v);
    }
    onChange(next);
    setSelectedPicked([]);
  };

  const addAll = (): void => {
    onChange(new Set(items.map((i) => i.value)));
    setAvailablePicked([]);
  };

  const clearAll = (): void => {
    onChange(new Set());
    setSelectedPicked([]);
  };

  return (
    <div className="grid gap-3 md:grid-cols-[1fr_48px_1fr]">
      <div className="flex h-[460px] flex-col overflow-hidden rounded-xl border">
        <div className="flex shrink-0 items-center gap-2 border-b px-3 py-2.5">
          <List className="text-muted-foreground size-4 shrink-0" />
          <span className="text-sm font-medium">可选频道</span>
          <Badge className="ml-auto" variant="secondary">
            {availableItems.length}
          </Badge>
        </div>
        {error ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-3 p-6 text-center">
            <WifiOff className="text-muted-foreground size-8" />
            <p className="text-muted-foreground text-sm">加载失败，请重试</p>
            <Button onClick={onReload} size="sm" variant="destructive">
              重试
            </Button>
          </div>
        ) : (
          <Listbox
            emptyIcon={<Inbox className="text-muted-foreground size-7" />}
            emptyText="暂无可选频道"
            items={availableItems}
            loading={loading}
            onPicked={setAvailablePicked}
            picked={availablePicked}
          />
        )}
      </div>

      <div className="flex flex-row items-center justify-center gap-1 md:flex-col md:pt-10">
        <Button
          disabled={availableItems.length === 0}
          onClick={addAll}
          size="icon"
          variant="ghost"
        >
          <ChevronsRight />
        </Button>
        <Button
          disabled={availablePicked.length === 0}
          onClick={addPicked}
          size="icon"
        >
          <ChevronRight />
        </Button>
        <Button
          disabled={selectedPicked.length === 0}
          onClick={removePicked}
          size="icon"
          variant="secondary"
        >
          <ChevronLeft />
        </Button>
      </div>

      <div className="flex h-[460px] flex-col overflow-hidden rounded-xl border">
        <div className="flex shrink-0 items-center gap-2 border-b px-3 py-2.5">
          <CheckCircle className="size-4 shrink-0 text-green-500" />
          <span className="text-sm font-medium">已选频道</span>
          {selectedItems.length > 0 ? (
            <>
              <Badge className="ml-auto" variant="success">
                {selectedItems.length}
              </Badge>
              <Button onClick={clearAll} size="sm" variant="ghost">
                清空
              </Button>
            </>
          ) : null}
        </div>
        <Listbox
          emptyIcon={
            <ArrowLeftRight className="text-muted-foreground size-7" />
          }
          emptyText="从左侧选择要转发的频道"
          items={selectedItems}
          loading={loading}
          onPicked={setSelectedPicked}
          picked={selectedPicked}
        />
      </div>
    </div>
  );
};

// app/components/selector/target/transfer-list.vue
<template>
  <div class="grid gap-3 md:grid-cols-[1fr_48px_1fr]">
    <!-- 可选面板 -->
    <div
      class="border-default flex min-h-[340px] flex-col overflow-hidden rounded-xl border"
    >
      <div
        class="border-default flex shrink-0 items-center gap-2 border-b px-3 py-2.5"
      >
        <UIcon name="i-lucide-list" class="text-muted size-4 shrink-0" />
        <span class="text-sm font-medium">可选频道</span>
        <UBadge variant="subtle" size="sm" class="ml-auto">
          {{ availableItems.length }}
        </UBadge>
      </div>

      <div
        v-if="error"
        class="flex flex-1 flex-col items-center justify-center gap-3 p-6 text-center"
      >
        <UIcon name="i-lucide-wifi-off" class="text-muted size-8" />
        <p class="text-muted text-sm">加载失败，请重试</p>
        <UButton size="sm" color="error" variant="soft" @click="reload">
          重试
        </UButton>
      </div>

      <UListbox
        v-else
        v-model="availablePicked"
        multiple
        value-key="value"
        class="min-h-0 flex-1"
        :items="availableItems"
        :loading="loading"
        :filter="{ placeholder: '搜索...' }"
      >
        <template #empty>
          <div class="flex flex-col items-center gap-2 py-10 text-center">
            <UIcon
              v-if="!loading"
              name="i-lucide-inbox"
              class="text-muted size-7"
            />
            <span class="text-muted text-sm">{{
              loading ? "加载中..." : "暂无可选频道"
            }}</span>
          </div>
        </template>
      </UListbox>
    </div>

    <!-- 中间操作列 -->
    <div
      class="flex flex-row items-center justify-center gap-1 md:flex-col md:pt-10"
    >
      <UTooltip text="全部添加" :delay-duration="300">
        <UButton
          icon="i-lucide-chevrons-right"
          color="neutral"
          variant="ghost"
          size="sm"
          :disabled="availableItems.length === 0"
          @click="addAll"
        />
      </UTooltip>
      <UTooltip text="添加选中" :delay-duration="300">
        <UButton
          icon="i-lucide-chevron-right"
          size="sm"
          :disabled="availablePicked.length === 0"
          @click="addPicked"
        />
      </UTooltip>
      <USeparator
        orientation="horizontal"
        class="my-1 hidden w-6 self-center md:block"
      />
      <UTooltip text="移除选中" :delay-duration="300">
        <UButton
          icon="i-lucide-chevron-left"
          color="neutral"
          variant="soft"
          size="sm"
          :disabled="selectedPicked.length === 0"
          @click="removePicked"
        />
      </UTooltip>
    </div>

    <!-- 已选面板 -->
    <div
      class="border-default flex min-h-[340px] flex-col overflow-hidden rounded-xl border"
    >
      <div
        class="border-default flex shrink-0 items-center gap-2 border-b px-3 py-2.5"
      >
        <UIcon
          name="i-lucide-check-circle"
          class="text-success size-4 shrink-0"
        />
        <span class="text-sm font-medium">已选频道</span>
        <UBadge
          v-if="selectedItems.length > 0"
          color="success"
          variant="subtle"
          size="sm"
          class="ml-auto"
        >
          {{ selectedItems.length }}
        </UBadge>
        <UButton
          v-if="selectedItems.length > 0"
          size="xs"
          variant="ghost"
          color="neutral"
          :class="selectedItems.length === 0 ? 'ml-auto' : ''"
          @click="clearAll"
        >
          清空
        </UButton>
      </div>

      <UListbox
        v-model="selectedPicked"
        multiple
        value-key="value"
        class="min-h-0 flex-1"
        :items="selectedItems"
        :loading="loading"
        :filter="{ placeholder: '搜索...' }"
      >
        <template #empty>
          <div class="flex flex-col items-center gap-2 py-10 text-center">
            <UIcon
              v-if="!loading"
              name="i-lucide-arrow-left-right"
              class="text-muted size-7"
            />
            <span class="text-muted text-sm">{{
              loading ? "加载中..." : "从左侧选择要转发的频道"
            }}</span>
          </div>
        </template>
      </UListbox>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ComputedRef, Ref } from "vue";
import { computed, ref, watch } from "vue";

export interface TransferItem {
  avatar?: { src: string };
  description?: string;
  label: string;
  value: string;
}

const props = defineProps<{
  error: string | null;
  items: TransferItem[];
  loading: boolean;
}>();

const emit = defineEmits<{
  reload: [];
}>();

const selected = defineModel<Set<string>>("selected", { required: true });

const availablePicked = ref<string[]>([]);
const selectedPicked = ref<string[]>([]);

const selectedItems = computed(() =>
  props.items.filter((item) => selected.value.has(item.value)),
);

const availableItems = computed(() =>
  props.items.filter((item) => !selected.value.has(item.value)),
);

const setSelected = (nextValues: Iterable<string>) => {
  selected.value = new Set(nextValues);
};

const addPicked = () => {
  if (availablePicked.value.length === 0) {
    return;
  }

  const next = new Set(selected.value);
  for (const value of availablePicked.value) {
    next.add(value);
  }
  setSelected(next);
  availablePicked.value = [];
};

const removePicked = () => {
  if (selectedPicked.value.length === 0) {
    return;
  }

  const next = new Set(selected.value);
  for (const value of selectedPicked.value) {
    next.delete(value);
  }
  setSelected(next);
  selectedPicked.value = [];
};

const addAll = () => {
  setSelected(props.items.map((item) => item.value));
  availablePicked.value = [];
};

const clearAll = () => {
  setSelected([]);
  selectedPicked.value = [];
};

const reload = () => {
  emit("reload");
};

const syncPicked = (
  picked: Ref<string[]>,
  items: ComputedRef<TransferItem[]>,
) => {
  watch(
    () => items.value.map((item) => item.value),
    (values) => {
      const valid = new Set(values);
      picked.value = picked.value.filter((value) => valid.has(value));
    },
    { immediate: true },
  );
};

syncPicked(availablePicked, availableItems);
syncPicked(selectedPicked, selectedItems);
</script>
