// app/components/loading-state.vue
<template>
  <div class="py-12">
    <div class="flex flex-col items-center gap-3">
      <UIcon name="i-lucide-loader-2" class="text-muted size-6 animate-spin" />
      <p class="text-muted text-sm">{{ displayText }}</p>
    </div>
  </div>
</template>

<script lang="ts" setup>
const props = defineProps<{ text?: string }>();

const displayText = computed(() => props.text ?? "正在加载配置...");
</script>

// apps/web/src/components/common/loading-state.tsx
import { Loader2 } from "lucide-react";

/** 居中的加载占位。 */
export const LoadingState = ({ text }: { text?: string }) => (
  <div className="py-12">
    <div className="flex flex-col items-center gap-3">
      <Loader2 className="text-muted-foreground size-6 animate-spin" />
      <p className="text-muted-foreground text-sm">
        {text ?? "正在加载配置..."}
      </p>
    </div>
  </div>
);
