// apps/web/src/pages/players.tsx
import { Search } from "lucide-react";
import { useMemo, useState } from "react";

import { LoadingState } from "@/components/common/loading-state";
import { PageHeader } from "@/components/layout/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { usePlayers } from "@/queries/players";

const PAGE_SIZE = 10;

export const PlayersPage = () => {
  const { data: playerList } = usePlayers();
  const [search, setSearch] = useState("");
  const [pageIndex, setPageIndex] = useState(0);

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return (playerList ?? []).filter((p) => {
      if (!q) {
        return true;
      }
      return (
        p.player.name.toLowerCase().includes(q) ||
        p.player.uuid.toLowerCase().includes(q) ||
        (p.player.ip ?? "").toLowerCase().includes(q) ||
        (p.socialAccount?.uid ?? "").toLowerCase().includes(q)
      );
    });
  }, [playerList, search]);

  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const safePage = Math.min(pageIndex, pageCount - 1);
  const pageRows = filtered.slice(
    safePage * PAGE_SIZE,
    safePage * PAGE_SIZE + PAGE_SIZE,
  );

  return (
    <>
      <PageHeader
        width="full"
        description="查看你的玩家，查看玩家的社交账号绑定情况及所在服务器。"
        title="玩家列表"
      />
      <div className="scrollbar-custom flex-1 overflow-y-auto">
        <div className="border-b">
          <div className="flex items-center gap-2 px-4 lg:px-6">
            <Search className="text-muted-foreground size-4 shrink-0" />
            <Input
              className="border-none px-0 shadow-none focus-visible:ring-0"
              onChange={(e) => {
                setSearch(e.target.value);
                setPageIndex(0);
              }}
              placeholder="搜索玩家名、UUID、IP 或社交账号..."
              value={search}
            />
          </div>
        </div>
        {playerList === undefined ? (
          <LoadingState />
        ) : (
          <>
            <Table>
              <TableHeader>
                <TableRow className="bg-muted/50">
                  <TableHead className="pl-4 lg:pl-6">玩家名</TableHead>
                  <TableHead>UUID</TableHead>
                  <TableHead>IP 地址</TableHead>
                  <TableHead>社交账号</TableHead>
                  <TableHead className="pr-4 lg:pr-6">所在服务器</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {pageRows.length === 0 ? (
                  <TableRow>
                    <TableCell
                      className="text-muted-foreground py-8 text-center text-sm"
                      colSpan={5}
                    >
                      暂无玩家数据
                    </TableCell>
                  </TableRow>
                ) : (
                  pageRows.map((p) => (
                    <TableRow key={p.player.uuid}>
                      <TableCell className="pl-4 lg:pl-6">
                        {p.player.name}
                      </TableCell>
                      <TableCell className="font-mono text-xs">
                        {p.player.uuid}
                      </TableCell>
                      <TableCell>{p.player.ip ?? "—"}</TableCell>
                      <TableCell>
                        {p.socialAccount ? (
                          <div className="flex items-center gap-2">
                            <Badge variant="secondary">
                              {p.socialAccount.platform}
                            </Badge>
                            <span className="text-muted-foreground text-sm">
                              {p.socialAccount.nickname ?? ""} (
                              {p.socialAccount.uid})
                            </span>
                          </div>
                        ) : (
                          <Badge variant="destructive">未绑定</Badge>
                        )}
                      </TableCell>
                      <TableCell className="pr-4 lg:pr-6">
                        {p.serversName.join(", ") || "—"}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
            <div className="border-t">
              <div className="flex items-center justify-end gap-2 px-4 py-4 lg:px-6">
                <span className="text-muted-foreground text-sm">
                  第 {safePage + 1} / {pageCount} 页 · 共 {filtered.length} 条
                </span>
                <Button
                  disabled={safePage === 0}
                  onClick={() => {
                    setPageIndex((i) => Math.max(0, i - 1));
                  }}
                  size="sm"
                  variant="outline"
                >
                  上一页
                </Button>
                <Button
                  disabled={safePage >= pageCount - 1}
                  onClick={() => {
                    setPageIndex((i) => Math.min(pageCount - 1, i + 1));
                  }}
                  size="sm"
                  variant="outline"
                >
                  下一页
                </Button>
              </div>
            </div>
          </>
        )}
      </div>
    </>
  );
};

// app/pages/players.vue
<script lang="ts" setup>
import type { TableColumn } from "@nuxt/ui";
import { getPaginationRowModel } from "@tanstack/vue-table";
import type { z } from "zod";
import type { PlayerAPI } from "~~/shared/schemas/player";

import PageHeader from "@/components/header/page-header.vue";
import { PlayerData } from "~/composables/api";

const UBadge = resolveComponent("UBadge");

const toast = useToast();
const playerList = ref<z.infer<typeof PlayerAPI.GETS.response>>([]);
const isLoadingList = ref(false);

const fetchPlayerList = async () => {
  isLoadingList.value = true;
  try {
    playerList.value = await PlayerData.gets();
  } catch (error) {
    console.error("Failed to fetch player list:", error);
    toast.add({ color: "error", title: "获取玩家列表失败" });
  } finally {
    isLoadingList.value = false;
  }
};

onMounted(() => {
  fetchPlayerList();
});

const searchName = ref("");
const searchUUID = ref("");
const searchIP = ref("");
const searchSocial = ref("");

interface PlayerRow {
  ip: string | null;
  name: string;
  serversName: string;
  socialAccount: z.infer<
    typeof PlayerAPI.GETS.response
  >[number]["socialAccount"];
  uuid: string;
}

const table = useTemplateRef("table");
const pagination = ref({ pageIndex: 0, pageSize: 10 });

watch([searchName, searchUUID, searchIP, searchSocial], () => {
  pagination.value.pageIndex = 0;
});

const data = computed<PlayerRow[]>(() =>
  playerList.value
    .map((player) => ({
      ip: player.player.ip,
      name: player.player.name,
      serversName: player.serversName.join(", "),
      socialAccount: player.socialAccount,
      uuid: player.player.uuid,
    }))
    .filter(
      (player) =>
        player.name.toLowerCase().includes(searchName.value.toLowerCase()) &&
        player.uuid.toLowerCase().includes(searchUUID.value.toLowerCase()) &&
        (player.ip ?? "")
          .toLowerCase()
          .includes(searchIP.value.toLowerCase()) &&
        (player.socialAccount?.uid ?? "")
          .toLowerCase()
          .includes(searchSocial.value.toLowerCase()),
    ),
);

const columns: TableColumn<PlayerRow>[] = [
  {
    accessorKey: "name",
    header: "玩家名",
  },
  {
    accessorKey: "uuid",
    header: "UUID",
  },
  {
    accessorKey: "ip",
    cell: ({ row }) => row.original.ip ?? "—",
    header: "IP 地址",
  },
  {
    accessorKey: "socialAccount",
    cell: ({ row }) => {
      const sa = row.original.socialAccount;
      if (sa) {
        return h("div", { class: "flex items-center gap-2" }, [
          h(
            UBadge,
            { color: "info", size: "sm", variant: "subtle" },
            () => sa.adapterType,
          ),
          h(
            "span",
            { class: "text-muted text-sm" },
            `${sa.nickname ?? ""} (${sa.uid})`,
          ),
        ]);
      }
      return h(
        UBadge,
        { color: "error", size: "sm", variant: "subtle" },
        () => "未绑定",
      );
    },
    header: "社交账号",
  },
  {
    accessorKey: "serversName",
    cell: ({ row }) => row.original.serversName || "—",
    header: "所在服务器",
  },
];
</script>

<template>
  <div class="h-full">
    <UDashboardPanel
      class="scrollbar-custom h-full"
      :ui="{ body: 'p-0 sm:p-0 overflow-y-auto overscroll-none' }"
    >
      <template #header>
        <PageHeader
          title="玩家列表"
          description="查看你的玩家，查看玩家的社交账号绑定情况及所在服务器。"
        />
      </template>
      <template #body>
        <UContainer class="py-8">
          <!-- 搜索栏 -->
          <div class="mb-4 grid grid-cols-1 gap-3 md:grid-cols-4">
            <UInput
              v-model="searchName"
              icon="i-lucide-search"
              placeholder="搜索玩家名..."
            />
            <UInput
              v-model="searchUUID"
              icon="i-lucide-search"
              placeholder="搜索UUID..."
            />
            <UInput
              v-model="searchIP"
              icon="i-lucide-search"
              placeholder="搜索IP..."
            />
            <UInput
              v-model="searchSocial"
              icon="i-lucide-search"
              placeholder="搜索社交账号UID..."
            />
          </div>

          <!-- 表格 -->
          <UTable
            ref="table"
            v-model:pagination="pagination"
            :data="data"
            :columns="columns"
            :loading="isLoadingList"
            :pagination-options="{
              getPaginationRowModel: getPaginationRowModel(),
            }"
          >
            <template #empty>
              <div class="text-muted py-8 text-center text-sm">
                暂无玩家数据
              </div>
            </template>
          </UTable>

          <!-- 分页 -->
          <div class="border-default mt-4 flex justify-end border-t px-4 pt-4">
            <UPagination
              v-model:page="pagination.pageIndex"
              :items-per-page="pagination.pageSize"
              :total="data.length"
            />
          </div>
        </UContainer>
      </template>
    </UDashboardPanel>
  </div>
</template>
