// apps/web/src/pages/servers/command.tsx
import { useQuery } from "@tanstack/react-query";
import { useNavigate, useParams } from "@tanstack/react-router";
import { differenceWith, isEqual, pick } from "lodash-es";
import { TriangleAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { PlatformType } from "#shared/model/bot/types";
import { CommandConfigSchema } from "#shared/model/server/schema/command";
import type { targetResponse } from "#shared/model/server/schema/target";
import { LoadingState } from "@/components/common/loading-state";
import { MultiSelectCombobox } from "@/components/common/multi-select-combobox";
import {
  SettingsBlock,
  SettingsRow,
  SettingsSection,
} from "@/components/common/settings-section";
import { ServerHeader } from "@/components/layout/server-header";
import { TargetConfigSheet } from "@/components/target/target-config-sheet";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "@/components/ui/sonner";
import { Switch } from "@/components/ui/switch";
import { useRegisterPageState } from "@/hooks/use-page-state";
import { BotData, BrowserData, CommandData } from "@/lib/api";
import { errorMessage } from "@/lib/http";
import { ONEBOT_ROLES } from "@/lib/permissions";
import { useBot } from "@/queries/bots";
import { useServer } from "@/queries/servers";

const TargetCommandDrawer = ({
  target,
  platform,
  botId,
  onChange,
}: {
  target: targetResponse;
  platform: PlatformType | undefined;
  botId: number | undefined;
  onChange: (config: targetResponse["config"]) => void;
}) => {
  const cmd = target.config.CommandConfigSchema;

  const discordRoles = useQuery({
    enabled:
      platform === PlatformType.Discord &&
      botId !== undefined &&
      target.type === "group" &&
      target.guildId !== null,
    queryFn: async () => BotData.getDiscordRoles(botId!, target.guildId!),
    queryKey: ["discord-roles", botId, target.guildId],
  });

  const roleOptions =
    platform === PlatformType.Onebot ? ONEBOT_ROLES : (discordRoles.data ?? []);

  const setCmd = (patch: Partial<typeof cmd>): void => {
    onChange({
      ...target.config,
      CommandConfigSchema: { ...cmd, ...patch },
    });
  };

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center justify-between">
        <Label>远程指令</Label>
        <Switch
          checked={cmd.enabled}
          onCheckedChange={(v) => {
            setCmd({ enabled: v });
          }}
        />
      </div>
      <div className="space-y-1.5">
        <Label>指令前缀</Label>
        <Input
          onChange={(e) => {
            setCmd({ prefix: e.target.value });
          }}
          placeholder="请输入指令前缀（可空）"
          value={cmd.prefix}
        />
      </div>
      {target.type === "group" ? (
        <div className="space-y-2">
          <Label>权限</Label>
          <p className="text-muted-foreground text-xs">
            权限相互独立，不存在继承关系
          </p>
          {platform ? null : (
            <Alert variant="warning">
              <TriangleAlert />
              <AlertDescription>
                由于你没有选择 Bot 实例，无法提供权限建议，可手动输入
              </AlertDescription>
            </Alert>
          )}
          <MultiSelectCombobox
            creatable
            onChange={(permissions) => {
              setCmd({ permissions });
            }}
            options={roleOptions}
            placeholder="选择或输入权限"
            value={cmd.permissions}
          />
        </div>
      ) : null}
    </div>
  );
};

// oxlint-disable-next-line eslint/complexity
export const ServerCommandPage = () => {
  const { id } = useParams({ from: "/dashboard/servers/$id/command" });
  const serverId = Number(id);
  const navigate = useNavigate();

  const { data: server, refetch } = useServer(serverId);
  const { data: bot } = useBot(server?.botId ?? null);
  const { data: browser } = useQuery({
    queryFn: async () => BrowserData.get(),
    queryKey: ["browser-config"],
  });

  const [config, setConfig] = useState(CommandConfigSchema.parse({}));
  const [targets, setTargets] = useState<targetResponse[]>([]);
  const [original, setOriginal] = useState<{
    config: typeof config;
    targets: targetResponse[];
  } | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);

  useEffect(() => {
    if (server) {
      const nextConfig = server.commandConfig ?? CommandConfigSchema.parse({});
      setConfig(nextConfig);
      setTargets(server.targets);
      setOriginal({
        config: structuredClone(nextConfig),
        targets: structuredClone(server.targets),
      });
    }
  }, [server]);

  const isDirty = useMemo(
    () => original !== null && !isEqual({ config, targets }, original),
    [config, targets, original],
  );

  const handleSubmit = async (): Promise<void> => {
    if (!original) {
      return;
    }
    const changed = differenceWith(targets, original.targets, isEqual).map(
      (t) => pick(t, ["id", "config"]),
    );
    try {
      await CommandData.patch(serverId, { command: config, targets: changed });
      toast.success("配置已保存");
      setSelectedId(null);
      await refetch();
    } catch (error) {
      toast.error("保存配置失败", { description: errorMessage(error) });
    }
  };

  useRegisterPageState(
    isDirty,
    async () => handleSubmit(),
    () => {
      setConfig(
        structuredClone(original?.config ?? CommandConfigSchema.parse({})),
      );
      setTargets(structuredClone(original?.targets ?? []));
      setSelectedId(null);
    },
  );

  if (!original) {
    return (
      <>
        <ServerHeader />
        <div className="flex-1 overflow-y-auto p-6">
          <LoadingState />
        </div>
      </>
    );
  }

  return (
    <>
      <ServerHeader />
      <div className="scrollbar-custom flex-1 overflow-y-auto">
        <div className="mx-auto max-w-2xl px-4 py-8 lg:px-6">
          <div className="space-y-8">
            <SettingsSection title="基础设置">
              <SettingsRow
                description="将指令返回结果的颜色代码转换为图片后发送"
                label="图片渲染"
              >
                <Switch
                  checked={config.imageRender}
                  onCheckedChange={(v) => {
                    setConfig({ ...config, imageRender: v });
                  }}
                />
              </SettingsRow>
              {browser?.executablePath === null ? (
                <div className="pb-4">
                  <Alert variant="warning">
                    <TriangleAlert />
                    <AlertDescription>
                      <Button
                        className="h-auto p-0"
                        onClick={() => {
                          void navigate({ to: "/settings/browser" });
                        }}
                        variant="link"
                      >
                        图片渲染功能需要配置浏览器路径才能使用（去配置）
                      </Button>
                    </AlertDescription>
                  </Alert>
                </div>
              ) : null}
            </SettingsSection>

            <SettingsSection
              description="针对不同目标单独配置远程指令权限"
              title="目标配置"
            >
              <SettingsBlock>
                <TargetConfigSheet
                  onSelectedChange={setSelectedId}
                  selectedId={selectedId}
                  serverId={serverId}
                  targets={targets}
                >
                  {(target) => (
                    <TargetCommandDrawer
                      botId={bot?.id}
                      onChange={(newConfig) => {
                        setTargets((prev) =>
                          prev.map((t) =>
                            t.id === target.id
                              ? { ...t, config: newConfig }
                              : t,
                          ),
                        );
                      }}
                      platform={bot?.platform}
                      target={target}
                    />
                  )}
                </TargetConfigSheet>
              </SettingsBlock>
            </SettingsSection>
          </div>
        </div>
      </div>
    </>
  );
};

// app/pages/servers/[id]/command.vue
<template>
  <div class="h-full">
    <UDashboardPanel
      class="scrollbar-custom h-full"
      :ui="{ body: 'p-0 sm:p-0 overflow-y-auto overscroll-none' }"
    >
      <template #header>
        <ServerHeader />
      </template>
      <template #body>
        <UContainer class="py-8">
          <LoadingState v-if="!formData.config" />

          <template v-else>
            <div
              class="grid gap-4"
              :class="isMobile ? 'grid-cols-1' : 'grid-cols-2'"
            >
              <UPageCard variant="outline" title="基础设置">
                <UFormField
                  label="图片渲染"
                  description="将指令返回结果的颜色代码转换为图片后发送"
                >
                  <USwitch v-model="formData.config.imageRender" />
                </UFormField>
                <UAlert
                  v-if="currentConfig.executablePath === null"
                  color="warning"
                  variant="subtle"
                  icon="i-lucide-info"
                  class="mt-2"
                >
                  <template #description>
                    <UButton
                      variant="link"
                      color="warning"
                      size="sm"
                      class="p-0"
                      @click="router.push('/settings/browser')"
                    >
                      图片渲染功能需要配置浏览器路径才能使用（去配置）
                    </UButton>
                  </template>
                </UAlert>
              </UPageCard>
              <UPageCard
                variant="outline"
                title="配置群聊"
                description="单独对目标进行配置"
              >
                <UDropdownMenu
                  v-if="options.length"
                  :items="
                    options.map((o) => ({
                      label: o.label,
                      onSelect: () => handleSelect(o.key),
                    }))
                  "
                >
                  <UButton icon="i-lucide-settings-2">配置目标</UButton>
                </UDropdownMenu>
                <UAlert
                  v-else
                  color="warning"
                  variant="subtle"
                  icon="i-lucide-triangle-alert"
                >
                  <template #description>
                    <UButton
                      variant="link"
                      color="warning"
                      size="sm"
                      class="p-0"
                      @click="router.push(`/servers/${route.params.id}/target`)"
                    >
                      你还没有创建目标哦（去创建）
                    </UButton>
                  </template>
                </UAlert>
              </UPageCard>
            </div>

            <USlideover
              v-model:open="drawerVisible"
              :title="
                selectTarget
                  ? `目标配置 · ${selectTarget.channelId || selectTarget.id}`
                  : ''
              "
            >
              <template #body>
                <drawer-command
                  v-if="selectTarget"
                  :platformType="botData?.platform"
                  :botId="botData?.id"
                  :target="selectTarget"
                />
              </template>
            </USlideover>

            <USeparator class="my-4" />
            <div class="flex justify-end gap-2">
              <UButton
                color="neutral"
                variant="subtle"
                :disabled="isAnyLoading || !isDirty"
                :loading="isAnyLoading"
                @click="cancelChanges"
              >
                取消更改
              </UButton>
              <UButton
                :disabled="isAnyLoading || !isDirty"
                :loading="isAnyLoading"
                @click="handleSubmit"
              >
                保存配置
              </UButton>
            </div>
          </template>
        </UContainer>
      </template>
    </UDashboardPanel>
  </div>
</template>

<script lang="ts" setup>
import { differenceWith, isEqual, pick } from "lodash-es";
import type { z } from "zod";
import { pickEditableTarget } from "~~/shared/utils/target";

import type { BotWithStatus } from "#shared/model/bot/api";
import { CommandAPI } from "#shared/model/server/api";
import type { CommandConfig } from "#shared/model/server/schema/command";
import { CommandConfigSchema } from "#shared/model/server/schema/command";
import type { ServerWithStatus } from "#shared/model/server/schema/servers";
import type { targetResponse } from "#shared/model/server/schema/target";
import ServerHeader from "@/components/header/server-header.vue";
import { useIsMobile } from "@/composables/is-mobile";
import {
  BotData,
  BrowserData,
  CommandData,
  fetchErrorMsg,
  ServerData,
} from "~/composables/api";

const isMobile = useIsMobile();

const { setPageState, clearPageState } = usePageStateStore();

definePageMeta({ layout: "default" });

const route = useRoute();
const router = useRouter();
const toast = useToast();

interface FormState {
  config: CommandConfig | null;
  targets: targetResponse[];
}

const formData = reactive<FormState>({
  config: null,
  targets: [],
});

const selectTarget = ref<targetResponse | null>(null);
const drawerVisible = ref(false);
let serverData: ServerWithStatus | null = null;
const botData = ref<BotWithStatus | null>(null);
const currentConfig = ref<{
  executablePath: string | null | undefined;
}>({ executablePath: undefined });

const originalFormData = ref<FormState | null>(null);

const loadingMap = reactive({
  isLoading: true,
  isSubmitting: false,
});

const isDirty = computed(() => {
  if (!formData.config || !originalFormData.value?.config) {
    return false;
  }

  return !isEqual(formData, originalFormData.value);
});
const isAnyLoading = computed(() => Object.values(loadingMap).some(Boolean));

const options = ref<{ label: string; key: string }[]>([]);

const handleSelect = (key: string) => {
  drawerVisible.value = true;
  const selected = serverData?.targets.find(
    (t) => String(t.id) === String(key),
  );
  if (selected) {
    selectTarget.value = pickEditableTarget(selected, formData.targets);
  }
};

const refreshServerData = async (): Promise<void> => {
  if (!route.params["id"]) {
    loadingMap.isLoading = false;
    return;
  }
  loadingMap.isLoading = true;
  try {
    const data = await ServerData.get(Number(route.params["id"]));
    serverData = data;
    options.value = data.targets.map((target) => ({
      key: target.id,
      label: target.channelId,
    }));
    botData.value = data.botId ? await BotData.get(data.botId) : null;
    formData.config = structuredClone(
      data.commandConfig || CommandConfigSchema.parse({}),
    );
    formData.targets = structuredClone(data.targets || []);
    originalFormData.value = structuredClone(toRaw(formData));
  } catch (error) {
    toast.add({
      color: "error",
      description: fetchErrorMsg(error),
      title: "刷新服务器数据失败",
    });
  } finally {
    loadingMap.isLoading = false;
  }
};

const handleSubmit = async () => {
  if (!isDirty.value || !formData.config) {
    return;
  }

  const targetsPayload: z.infer<typeof CommandAPI.PATCH.request>["targets"] =
    differenceWith(
      formData.targets,
      originalFormData.value?.targets || [],
      isEqual,
    ).map((t) => pick(t, ["id", "config"]));

  loadingMap.isSubmitting = true;
  try {
    await CommandData.patch(Number(route.params["id"]), {
      command: formData.config,
      targets: targetsPayload,
    });
    toast.add({ color: "success", title: "配置已保存" });
    selectTarget.value = null;
    await refreshServerData();
  } catch (error) {
    toast.add({
      color: "error",
      description: fetchErrorMsg(error),
      title: "保存配置失败",
    });
  } finally {
    loadingMap.isSubmitting = false;
  }
};

const cancelChanges = () => {
  if (originalFormData.value) {
    Object.assign(formData, structuredClone(toRaw(originalFormData.value)));
  } else {
    formData.config = null;
    formData.targets = [];
  }
  selectTarget.value = null;
};

const loadConfig = async () => {
  loadingMap.isLoading = true;
  try {
    const data = await BrowserData.get();
    currentConfig.value = data ?? { executablePath: null };
  } catch {
    toast.add({ color: "error", title: "加载配置失败" });
  } finally {
    loadingMap.isLoading = false;
  }
};

onMounted(async () => {
  await refreshServerData();
  await loadConfig();
  setPageState({ isDirty: () => isDirty.value, save: handleSubmit });
});

onUnmounted(() => {
  clearPageState();
});
</script>
