// apps/web/src/pages/servers/msgbridge.tsx
import { useLocation, useParams } from "@tanstack/react-router";
import { differenceWith, isEqual, pick } from "lodash-es";
import { MessageSquare, Settings, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { z } from "zod";

import type { ChatSyncConfigSchema } from "#shared/model/server/schema/chat-sync";
import type { targetResponse } from "#shared/model/server/schema/target";
import {
  formatMCToPlatformMessage,
  formatPlatformToMCMessage,
} from "#shared/utils/chat-sync";
import { LoadingState } from "@/components/common/loading-state";
import {
  SettingsBlock,
  SettingsRow,
  SettingsSection,
  SubPageLayout,
} from "@/components/common/settings-section";
import type { SubNavItem } from "@/components/common/settings-section";
import { useLayout } from "@/components/layout/context";
import { MessageTemplateField } from "@/components/target/message-template-field";
import { TargetConfigSheet } from "@/components/target/target-config-sheet";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "@/components/ui/sonner";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { useRegisterPageState } from "@/hooks/use-page-state";
import { ChatSyncData } from "@/lib/api";
import { errorMessage } from "@/lib/http";
import { findMenuNode } from "@/lib/menu";
import {
  MC_TO_PLATFORM_VARS,
  PLATFORM_TO_MC_VARS,
} from "@/lib/template-variables";
import { useServer } from "@/queries/servers";
import { usePageStateStore } from "@/stores/page-state";

type ChatSyncConfig = z.infer<typeof ChatSyncConfigSchema>;
type ArrayFilterKey =
  | "blacklistKeywords"
  | "blacklistRegex"
  | "whitelistPrefixes"
  | "whitelistRegex";

const NAV_ITEMS: SubNavItem[] = [
  {
    description: "启用、前缀过滤",
    icon: Settings,
    label: "基础配置",
    value: "basic",
  },
  {
    description: "自定义消息格式",
    icon: MessageSquare,
    label: "消息模板",
    value: "templates",
  },
  {
    description: "绑定聊天群组",
    icon: Users,
    label: "群聊目标",
    value: "targets",
  },
];

const ArrayField = ({
  label,
  desc,
  value,
  onChange,
  multiline,
  placeholder,
}: {
  label: string;
  desc: string;
  value: string[];
  onChange: (next: string[]) => void;
  multiline?: boolean;
  placeholder: string;
}) => {
  const text = value.join(",");
  const update = (raw: string): void => {
    onChange(
      raw
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
    );
  };
  return (
    <SettingsBlock>
      <div className="space-y-1.5">
        <p className="text-sm font-medium">{label}</p>
        <p className="text-muted-foreground text-xs">{desc}</p>
        {multiline ? (
          <Textarea
            onChange={(e) => {
              update(e.target.value);
            }}
            placeholder={placeholder}
            rows={2}
            value={text}
          />
        ) : (
          <Input
            onChange={(e) => {
              update(e.target.value);
            }}
            placeholder={placeholder}
            value={text}
          />
        )}
      </div>
    </SettingsBlock>
  );
};

// 视图容器：三分区 + 目标抽屉，分支较多但均为展示逻辑。
// oxlint-disable-next-line eslint/complexity
export const ServerMsgbridgePage = () => {
  const { id } = useParams({ from: "/dashboard/servers/$id/msgbridge" });
  const serverId = Number(id);
  const { menu } = useLayout();
  const { pathname } = useLocation();
  const node = findMenuNode(menu, pathname);
  const dirty = usePageStateStore((s) => s.dirty);
  const savePage = usePageStateStore((s) => s.savePage);
  const cancelPage = usePageStateStore((s) => s.cancelPage);

  const { data: server, refetch } = useServer(serverId);

  const [config, setConfig] = useState<ChatSyncConfig | null>(null);
  const [targets, setTargets] = useState<targetResponse[]>([]);
  const [original, setOriginal] = useState<{
    config: ChatSyncConfig;
    targets: targetResponse[];
  } | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [section, setSection] = useState("basic");

  useEffect(() => {
    if (server) {
      setConfig(server.chatSyncConfig);
      setTargets(server.targets);
      setOriginal({
        config: structuredClone(server.chatSyncConfig),
        targets: structuredClone(server.targets),
      });
    }
  }, [server]);

  const isDirty = useMemo(
    () =>
      original !== null &&
      config !== null &&
      !isEqual({ config, targets }, original),
    [config, targets, original],
  );

  const handleSubmit = async (): Promise<void> => {
    if (!(original && config)) {
      return;
    }
    const changed = differenceWith(targets, original.targets, isEqual).map(
      (t) => pick(t, ["id", "config"]),
    );
    try {
      await ChatSyncData.patch(serverId, {
        chatsync: config,
        targets: changed,
      });
      toast.success("消息同步配置已保存");
      setSelectedId(null);
      await refetch();
    } catch (error) {
      toast.error("保存配置失败", { description: errorMessage(error) });
    }
  };

  useRegisterPageState(
    isDirty,
    async () => {
      await handleSubmit();
    },
    () => {
      setConfig(structuredClone(original?.config ?? null));
      setTargets(structuredClone(original?.targets ?? []));
      setSelectedId(null);
    },
  );

  if (!(original && config)) {
    return (
      <>
        <div className="flex-1 overflow-y-auto p-6">
          <LoadingState />
        </div>
      </>
    );
  }

  const setFilter = (patch: Partial<ChatSyncConfig["filters"]>): void => {
    setConfig({ ...config, filters: { ...config.filters, ...patch } });
  };
  const setArrayFilter = (key: ArrayFilterKey) => (next: string[]) => {
    setFilter({ [key]: next });
  };

  const dirtyActions = dirty ? (
    <div className="flex gap-2">
      <Button onClick={cancelPage} size="sm" variant="secondary">
        取消更改
      </Button>
      <Button
        onClick={() => {
          void savePage();
        }}
        size="sm"
      >
        保存配置
      </Button>
    </div>
  ) : undefined;

  return (
    <>
      <SubPageLayout
        headerActions={dirtyActions}
        items={NAV_ITEMS}
        onChange={setSection}
        title={node?.label ?? "消息互通"}
        value={section}
      >
        {section === "basic" && (
          <>
            <SettingsSection
              description="控制聊天同步功能的启用状态及消息方向"
              title="聊天同步"
            >
              <SettingsRow
                description="将 Minecraft 玩家消息转发到聊天平台"
                label="MC → 平台"
              >
                <Switch
                  checked={config.mcToPlatformEnabled}
                  onCheckedChange={(v) => {
                    setConfig({ ...config, mcToPlatformEnabled: v });
                  }}
                />
              </SettingsRow>
              <SettingsRow
                description="将聊天平台消息转发到 Minecraft 服务器"
                label="平台 → MC"
              >
                <Switch
                  checked={config.platformToMcEnabled}
                  onCheckedChange={(v) => {
                    setConfig({ ...config, platformToMcEnabled: v });
                  }}
                />
              </SettingsRow>
            </SettingsSection>

            <SettingsSection
              description="配置消息长度限制和内容过滤规则"
              title="消息过滤"
            >
              <SettingsRow
                description="低于此长度的消息将被忽略"
                label="最小长度"
              >
                <Input
                  className="w-28 text-right"
                  onChange={(e) => {
                    setFilter({
                      minMessageLength: Number(e.target.value),
                    });
                  }}
                  type="number"
                  value={config.filters.minMessageLength}
                />
              </SettingsRow>
              <SettingsRow
                description="超过此长度的消息将被截断或忽略"
                label="最大长度"
              >
                <Input
                  className="w-28 text-right"
                  onChange={(e) => {
                    setFilter({
                      maxMessageLength: Number(e.target.value),
                    });
                  }}
                  type="number"
                  value={config.filters.maxMessageLength}
                />
              </SettingsRow>
              <SettingsRow label="过滤模式">
                <div className="flex gap-2">
                  <Button
                    onClick={() => {
                      setFilter({ filterMode: "blacklist" });
                    }}
                    size="sm"
                    variant={
                      config.filters.filterMode === "blacklist"
                        ? "default"
                        : "outline"
                    }
                  >
                    黑名单
                  </Button>
                  <Button
                    onClick={() => {
                      setFilter({ filterMode: "whitelist" });
                    }}
                    size="sm"
                    variant={
                      config.filters.filterMode === "whitelist"
                        ? "default"
                        : "outline"
                    }
                  >
                    白名单
                  </Button>
                </div>
              </SettingsRow>
              {config.filters.filterMode === "blacklist" ? (
                <>
                  <ArrayField
                    desc="包含这些关键词的消息将被过滤，不会转发"
                    label="屏蔽关键词"
                    onChange={setArrayFilter("blacklistKeywords")}
                    placeholder="用逗号分隔多个关键词，如：广告,刷屏,垃圾"
                    value={config.filters.blacklistKeywords}
                  />
                  <ArrayField
                    desc="匹配这些正则表达式的消息将被过滤"
                    label="屏蔽正则表达式"
                    multiline
                    onChange={setArrayFilter("blacklistRegex")}
                    placeholder="用逗号分隔多个正则表达式"
                    value={config.filters.blacklistRegex}
                  />
                </>
              ) : (
                <>
                  <ArrayField
                    desc="仅转发以这些前缀开头的消息"
                    label="允许前缀"
                    onChange={setArrayFilter("whitelistPrefixes")}
                    placeholder="用逗号分隔多个前缀，如：#,!,?"
                    value={config.filters.whitelistPrefixes}
                  />
                  <ArrayField
                    desc="仅转发匹配这些正则表达式的消息"
                    label="允许正则表达式"
                    multiline
                    onChange={setArrayFilter("whitelistRegex")}
                    placeholder="用逗号分隔多个正则表达式"
                    value={config.filters.whitelistRegex}
                  />
                </>
              )}
            </SettingsSection>
          </>
        )}

        {section === "templates" && (
          <>
            <SettingsSection
              description="Minecraft 玩家消息发送到平台时的格式"
              title={
                <span className="inline-flex items-center gap-2">
                  MC → 平台模板 <Badge>游戏到平台</Badge>
                </span>
              }
            >
              <SettingsBlock>
                <MessageTemplateField
                  label="模板内容"
                  multiline
                  onChange={(v) => {
                    setConfig({ ...config, mcToPlatformTemplate: v });
                  }}
                  preview={formatMCToPlatformMessage(
                    config.mcToPlatformTemplate,
                    {
                      message: "Hello world!",
                      playerName: "Steve",
                      playerUUID: "12345678-1234...",
                      serverName: server?.name ?? "",
                      timestamp: Date.now(),
                    },
                  )}
                  previewClassName="text-primary"
                  value={config.mcToPlatformTemplate}
                  variables={MC_TO_PLATFORM_VARS}
                />
              </SettingsBlock>
            </SettingsSection>

            <SettingsSection
              description="平台消息发送到 Minecraft 时的格式"
              title={
                <span className="inline-flex items-center gap-2">
                  平台 → MC 模板 <Badge variant="success">平台到游戏</Badge>
                </span>
              }
            >
              <SettingsBlock>
                <MessageTemplateField
                  label="模板内容"
                  multiline
                  onChange={(v) => {
                    setConfig({ ...config, platformToMcTemplate: v });
                  }}
                  preview={formatPlatformToMCMessage(
                    config.platformToMcTemplate,
                    {
                      message: "Hi everyone!",
                      nickname: "Alice",
                      platform: "Onebot",
                      timestamp: Date.now(),
                      userId: "123456789",
                    },
                  )}
                  value={config.platformToMcTemplate}
                  variables={PLATFORM_TO_MC_VARS}
                />
              </SettingsBlock>
            </SettingsSection>
          </>
        )}

        {section === "targets" && (
          <SettingsSection
            description="针对不同目标群聊进行单独配置"
            title="群聊目标配置"
          >
            <SettingsBlock>
              <TargetConfigSheet
                onSelectedChange={setSelectedId}
                selectedId={selectedId}
                serverId={serverId}
                targets={targets}
                triggerLabel="选择目标配置"
              >
                {(target) => (
                  <div className="flex items-center justify-between">
                    <Label>启用聊天同步</Label>
                    <Switch
                      checked={target.config.chatSyncConfigSchema.enabled}
                      onCheckedChange={(v) => {
                        setTargets((prev) =>
                          prev.map((t) =>
                            t.id === target.id
                              ? {
                                  ...t,
                                  config: {
                                    ...t.config,
                                    chatSyncConfigSchema: {
                                      ...t.config.chatSyncConfigSchema,
                                      enabled: v,
                                    },
                                  },
                                }
                              : t,
                          ),
                        );
                      }}
                    />
                  </div>
                )}
              </TargetConfigSheet>
            </SettingsBlock>
          </SettingsSection>
        )}
      </SubPageLayout>
    </>
  );
};

// app/pages/servers/[id]/msgbridge.vue
<template>
  <div class="h-full">
    <UDashboardPanel
      class="scrollbar-custom h-full"
      :ui="{ body: 'p-0 sm:p-0 overflow-y-auto overscroll-none' }"
    >
      <template #header>
        <ServerHeader />
        <UTabs
          v-model="activeTab"
          :content="false"
          :items="tabItems"
          variant="link"
        />
      </template>
      <template #body>
        <UContainer class="py-8">
          <LoadingState v-if="!formData.config" />

          <template v-else>
            <UForm
              ref="form"
              :schema="ChatSyncConfigSchema"
              :state="formData.config"
              @submit="onFormSubmit"
            >
              <!-- Tab 1: 基础配置 -->
              <div
                v-show="activeTab === 'basic'"
                class="grid gap-4"
                :class="isMobile ? 'grid-cols-1' : 'grid-cols-2'"
              >
                <!-- 开关状态总览 -->
                <UPageCard variant="outline">
                  <template #title>
                    <div class="flex items-center gap-2">
                      <span>聊天同步总开关</span>
                    </div>
                  </template>
                  <template #description>
                    <span class="text-muted text-sm"
                      >控制聊天同步功能的启用状态及消息方向</span
                    >
                  </template>
                  <template #default>
                    <div class="flex flex-col gap-4">
                      <USeparator />
                      <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <UFormField
                          name="mcToPlatformEnabled"
                          label="MC → 平台"
                          description="将 Minecraft 聊天消息转发至平台"
                        >
                          <USwitch
                            v-model="formData.config.mcToPlatformEnabled"
                          />
                        </UFormField>
                        <UFormField
                          name="platformToMcEnabled"
                          label="平台 → MC"
                          description="将平台消息转发至 Minecraft"
                        >
                          <USwitch
                            v-model="formData.config.platformToMcEnabled"
                          />
                        </UFormField>
                      </div>
                    </div>
                  </template>
                </UPageCard>

                <!-- 消息过滤 -->
                <UPageCard variant="outline" title="消息过滤">
                  <template #description>
                    <span class="text-muted text-sm"
                      >配置消息长度限制和内容过滤规则</span
                    >
                  </template>
                  <template #footer>
                    <div class="flex flex-col gap-4">
                      <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                        <UFormField
                          name="filters.minMessageLength"
                          label="最小长度"
                        >
                          <UInputNumber
                            v-model="formData.config.filters.minMessageLength"
                            class="w-full"
                            placeholder="最小消息字符数"
                          />
                        </UFormField>
                        <UFormField
                          name="filters.maxMessageLength"
                          label="最大长度"
                        >
                          <UInputNumber
                            v-model="formData.config.filters.maxMessageLength"
                            class="w-full"
                            placeholder="最大消息字符数"
                          />
                        </UFormField>
                      </div>
                      <UFormField
                        name="filters.filterMode"
                        label="过滤模式"
                        description="黑名单：转发全部消息但屏蔽指定内容；白名单：仅转发匹配的消息"
                      >
                        <URadioGroup
                          v-model="formData.config.filters.filterMode"
                          :items="[
                            { label: '黑名单模式', value: 'blacklist' },
                            { label: '白名单模式', value: 'whitelist' },
                          ]"
                          orientation="horizontal"
                        />
                      </UFormField>
                      <USeparator />
                      <template
                        v-if="
                          formData.config.filters.filterMode === 'blacklist'
                        "
                      >
                        <UFormField
                          name="filters.blacklistKeywords"
                          label="屏蔽关键词"
                          description="包含这些关键词的消息将被过滤，不会转发"
                        >
                          <UInput
                            v-model="blacklistKeywordsText"
                            placeholder="用逗号分隔多个关键词，如：广告,刷屏,垃圾"
                            class="w-full"
                          />
                        </UFormField>
                        <UFormField
                          name="filters.blacklistRegex"
                          label="屏蔽正则表达式"
                          description="匹配这些正则表达式的消息将被过滤，不会转发"
                        >
                          <UTextarea
                            v-model="blacklistRegexText"
                            placeholder="用逗号分隔多个正则表达式，如：^/.*,#spam.*"
                            :rows="2"
                            class="w-full"
                          />
                        </UFormField>
                      </template>
                      <template v-else>
                        <UFormField
                          name="filters.whitelistPrefixes"
                          label="允许前缀"
                          description="仅转发以这些前缀开头的消息"
                        >
                          <UInput
                            v-model="whitelistPrefixesText"
                            placeholder="用逗号分隔多个前缀，如：#,!,?"
                            class="w-full"
                          />
                        </UFormField>
                        <UFormField
                          name="filters.whitelistRegex"
                          label="允许正则表达式"
                          description="仅转发匹配这些正则表达式的消息"
                        >
                          <UTextarea
                            v-model="whitelistRegexText"
                            placeholder="用逗号分隔多个正则表达式，如：^#.*,#help.*"
                            :rows="2"
                            class="w-full"
                          />
                        </UFormField>
                      </template>
                    </div>
                  </template>
                </UPageCard>
              </div>

              <!-- Tab 2: 消息模板 -->
              <div
                v-show="activeTab === 'templates'"
                class="grid gap-4"
                :class="isMobile ? 'grid-cols-1' : 'grid-cols-2'"
              >
                <!-- MC → 平台模板 -->
                <UPageCard variant="outline">
                  <template #title>
                    <div class="flex items-center gap-2">
                      <span>MC → 平台模板</span>
                      <UBadge color="primary" variant="subtle" size="sm"
                        >游戏到平台</UBadge
                      >
                    </div>
                  </template>
                  <template #description>
                    <span class="text-muted text-sm"
                      >Minecraft 玩家消息发送到平台时的格式</span
                    >
                  </template>
                  <template #footer>
                    <UFormField name="mcToPlatformTemplate" label="模板内容">
                      <UTextarea
                        v-model="formData.config.mcToPlatformTemplate"
                        placeholder="MC 消息发送到平台的格式模板"
                        class="w-full"
                      />
                      <div class="mt-2 space-y-2">
                        <p class="text-muted text-xs">点击变量插入到模板</p>
                        <div class="flex flex-wrap gap-1">
                          <UTooltip
                            v-for="tag in mcToPlatformVariables"
                            :key="tag.value"
                            :text="`${tag.label} · [${tag.example}]`"
                          >
                            <UBadge
                              :color="
                                formData.config.mcToPlatformTemplate.includes(
                                  tag.value,
                                )
                                  ? 'primary'
                                  : 'neutral'
                              "
                              variant="subtle"
                              class="cursor-pointer"
                              @click="
                                insertPlaceholder(
                                  'mcToPlatformTemplate',
                                  tag.value,
                                )
                              "
                            >
                              {{ tag.value }}
                            </UBadge>
                          </UTooltip>
                        </div>
                        <div class="text-muted text-sm">
                          预览：
                          <span class="text-primary">{{
                            mcToPlatformPreview
                          }}</span>
                        </div>
                      </div>
                    </UFormField>
                  </template>
                </UPageCard>

                <!-- 平台 → MC 模板 -->
                <UPageCard
                  variant="outline"
                  description="平台消息发送到 Minecraft 时的格式"
                >
                  <template #title>
                    <div class="flex items-center gap-2">
                      <span>平台 → MC 模板</span>
                      <UBadge color="success" variant="subtle" size="sm"
                        >平台到游戏</UBadge
                      >
                    </div>
                  </template>
                  <template #footer>
                    <UFormField name="platformToMcTemplate" label="模板内容">
                      <UTextarea
                        v-model="formData.config.platformToMcTemplate"
                        placeholder="平台消息发送到 MC 的格式模板"
                        class="w-full"
                      />
                      <div class="mt-2 space-y-2">
                        <p class="text-muted text-xs">点击变量插入到模板</p>
                        <div class="flex flex-wrap gap-1">
                          <UTooltip
                            v-for="tag in platformToMcVariables"
                            :key="tag.value"
                            :text="`${tag.label} · [${tag.example}]`"
                          >
                            <UBadge
                              :color="
                                formData.config.platformToMcTemplate.includes(
                                  tag.value,
                                )
                                  ? 'success'
                                  : 'neutral'
                              "
                              variant="subtle"
                              class="cursor-pointer"
                              @click="
                                insertPlaceholder(
                                  'platformToMcTemplate',
                                  tag.value,
                                )
                              "
                            >
                              {{ tag.value }}
                            </UBadge>
                          </UTooltip>
                        </div>
                        <div class="text-muted text-sm">
                          预览：
                          <span class="text-success">{{
                            platformToMcPreview
                          }}</span>
                        </div>
                      </div>
                    </UFormField>
                  </template>
                </UPageCard>
              </div>

              <!-- Tab 3: 群聊目标 -->
              <div v-show="activeTab === 'targets'">
                <UPageCard variant="outline">
                  <template #title>群聊目标配置</template>
                  <template #description>
                    <span class="text-muted text-sm"
                      >针对不同目标群聊进行单独配置</span
                    >
                  </template>
                  <template #footer>
                    <UDropdownMenu
                      v-if="options.length"
                      :items="
                        options.map((o) => ({
                          label: o.label,
                          onSelect: () => handleSelect(o.key),
                        }))
                      "
                    >
                      <UButton icon="i-lucide-settings-2">选择目标配置</UButton>
                    </UDropdownMenu>
                    <UAlert
                      v-else
                      color="warning"
                      variant="subtle"
                      icon="i-lucide-triangle-alert"
                    >
                      <template #description>
                        <UButton
                          variant="link"
                          color="warning"
                          size="sm"
                          class="p-0"
                          @click="
                            router.push(`/servers/${route.params.id}/target`)
                          "
                        >
                          你还没有创建目标哦（去创建）
                        </UButton>
                      </template>
                    </UAlert>
                  </template>
                </UPageCard>
              </div>
            </UForm>

            <!-- 目标配置侧边栏 -->
            <USlideover
              v-model:open="drawerVisible"
              :title="
                selectTarget
                  ? `目标配置 · ${selectTarget.channelId || selectTarget.id}`
                  : ''
              "
            >
              <template #body>
                <div v-if="selectTarget">
                  <UFormField label="启用聊天同步" required>
                    <USwitch
                      v-model="selectTarget.config.chatSyncConfigSchema.enabled"
                    />
                  </UFormField>
                </div>
              </template>
            </USlideover>

            <!-- 操作按钮区 -->
            <USeparator class="my-4" />
            <div class="flex justify-end gap-2">
              <UButton
                color="neutral"
                variant="subtle"
                :disabled="!isDirty"
                :loading="isAnyLoading"
                @click="cancelChanges"
                >取消更改</UButton
              >
              <UButton
                :disabled="!isDirty"
                :loading="isAnyLoading"
                @click="form?.submit()"
              >
                保存配置
              </UButton>
            </div>
          </template>
        </UContainer>
      </template>
    </UDashboardPanel>
  </div>
</template>

<script lang="ts" setup>
import type { FormSubmitEvent } from "@nuxt/ui";
import { differenceWith, isEqual, pick } from "lodash-es";
import type { z } from "zod";
import {
  formatMCToPlatformMessage,
  formatPlatformToMCMessage,
} from "~~/shared/utils/chat-sync";
import { pickEditableTarget } from "~~/shared/utils/target";

import { ChatSyncAPI } from "#shared/model/server/api";
import type { ChatSyncConfig } from "#shared/model/server/schema/chat-sync";
import { ChatSyncConfigSchema } from "#shared/model/server/schema/chat-sync";
import type { ServerWithStatus } from "#shared/model/server/schema/servers";
import type { targetResponse } from "#shared/model/server/schema/target";
import ServerHeader from "@/components/header/server-header.vue";
import { useIsMobile } from "@/composables/is-mobile";
import { ChatSyncData, fetchErrorMsg, ServerData } from "~/composables/api";
import {
  createVariableMap,
  createVariablesArray,
} from "~/composables/use-placeholder-variables";

const isMobile = useIsMobile();

const { setPageState, clearPageState } = usePageStateStore();

export type ChatSyncPatchBody = z.infer<typeof ChatSyncAPI.PATCH.request>;

definePageMeta({ layout: "default" });

const tabItems = [
  { icon: "i-lucide-settings", label: "基础配置", value: "basic" },
  { icon: "i-lucide-message-square", label: "消息模板", value: "templates" },
  { icon: "i-lucide-users", label: "群聊目标", value: "targets" },
];

const activeTab = ref("basic");

const route = useRoute();
const router = useRouter();
const toast = useToast();
const form = useTemplateRef("form");

const selectTarget = ref<targetResponse | null>(null);
const drawerVisible = ref(false);
let serverData: ServerWithStatus | null = null;

interface FormState {
  config: ChatSyncConfig | null;
  targets: targetResponse[];
}

const formData = reactive<FormState>({
  config: null,
  targets: [],
});

const createArrayTextComputed = (
  key:
    | "blacklistKeywords"
    | "blacklistRegex"
    | "whitelistPrefixes"
    | "whitelistRegex",
) =>
  computed({
    get: () => {
      if (!formData.config) {
        return "";
      }

      return (formData.config.filters[key] || []).join(",");
    },
    set: (v: string) => {
      if (!formData.config) {
        return;
      }

      formData.config.filters[key] = v
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
    },
  });

const blacklistKeywordsText = createArrayTextComputed("blacklistKeywords");
const blacklistRegexText = createArrayTextComputed("blacklistRegex");
const whitelistPrefixesText = createArrayTextComputed("whitelistPrefixes");
const whitelistRegexText = createArrayTextComputed("whitelistRegex");

const originalFormData = ref<FormState | null>(null);

const loadingMap = reactive({
  isLoading: true,
  isSubmitting: false,
});

const isDirty = computed(() => {
  if (!formData.config || !originalFormData.value?.config) {
    return false;
  }

  return !isEqual(formData, originalFormData.value);
});
const isAnyLoading = computed(() => Object.values(loadingMap).some(Boolean));

const options = ref<{ label: string; key: string }[]>([]);

const handleSelect = (key: string) => {
  drawerVisible.value = true;
  const selected = serverData?.targets.find((t) => t.id === key) || null;
  if (selected) {
    selectTarget.value = pickEditableTarget(selected, formData.targets);
  }
};

// 占位符变量定义
const MC_TO_PLATFORM_VARIABLES_MAP = createVariableMap({
  "{message}": { example: "Hello world!", label: "消息内容" },
  "{playerName}": { example: "Steve", label: "玩家名" },
  "{playerUUID}": { example: "12345678-1234-1234...", label: "玩家 UUID" },
  "{serverName}": { example: "", label: "服务器名" },
  "{timestamp}": { example: Date.now(), label: "时间戳" },
});

const PLATFORM_TO_MC_VARIABLES_MAP = createVariableMap({
  "{message}": { example: "Hi everyone!", label: "消息内容" },
  "{nickname}": { example: "Alice", label: "昵称" },
  "{platform}": { example: "Onebot", label: "平台名" },
  "{timestamp}": { example: Date.now(), label: "时间戳" },
  "{userId}": { example: "123456789", label: "用户 ID" },
});

const mcToPlatformVariables = computed(() =>
  createVariablesArray(MC_TO_PLATFORM_VARIABLES_MAP),
);
const platformToMcVariables = computed(() =>
  createVariablesArray(PLATFORM_TO_MC_VARIABLES_MAP),
);

const mcToPlatformPreview = computed(() => {
  if (!formData.config) {
    return null;
  }

  return formatMCToPlatformMessage(formData.config.mcToPlatformTemplate, {
    message: MC_TO_PLATFORM_VARIABLES_MAP["{message}"].example,
    playerName: MC_TO_PLATFORM_VARIABLES_MAP["{playerName}"].example,
    playerUUID: MC_TO_PLATFORM_VARIABLES_MAP["{playerUUID}"].example,
    serverName: serverData?.name ?? "",
    timestamp: MC_TO_PLATFORM_VARIABLES_MAP["{timestamp}"].example,
  });
});

const platformToMcPreview = computed(() => {
  if (!formData.config) {
    return null;
  }

  return formatPlatformToMCMessage(formData.config.platformToMcTemplate, {
    message: PLATFORM_TO_MC_VARIABLES_MAP["{message}"].example,
    nickname: PLATFORM_TO_MC_VARIABLES_MAP["{nickname}"].example,
    platform: PLATFORM_TO_MC_VARIABLES_MAP["{platform}"].example,
    timestamp: PLATFORM_TO_MC_VARIABLES_MAP["{timestamp}"].example,
    userId: PLATFORM_TO_MC_VARIABLES_MAP["{userId}"].example,
  });
});

const insertPlaceholder = (
  field: keyof Pick<
    ChatSyncConfig,
    "mcToPlatformTemplate" | "platformToMcTemplate"
  >,
  placeholder: string,
) => {
  if (!formData.config) {
    return;
  }
  const current = formData.config[field] || "";
  formData.config[field] = current + placeholder;
};

const refreshServerData = async (): Promise<void> => {
  if (!route.params?.id) {
    loadingMap.isLoading = false;
    return;
  }
  loadingMap.isLoading = true;
  try {
    const data = await ServerData.get(Number(route.params["id"]));
    serverData = data;
    formData.config = structuredClone(data.chatSyncConfig);
    formData.targets = structuredClone(data.targets);
    originalFormData.value = structuredClone(toRaw(formData));
    options.value = data.targets.map((target) => ({
      key: target.id,
      label: target.channelId,
    }));
  } catch (error) {
    toast.add({
      color: "error",
      description: fetchErrorMsg(error),
      title: "刷新服务器数据失败",
    });
  } finally {
    loadingMap.isLoading = false;
  }
};

const handleSubmit = async () => {
  if (!isDirty.value || !formData.config) {
    return;
  }

  const targetsPayload: z.infer<typeof ChatSyncAPI.PATCH.request>["targets"] =
    differenceWith(
      formData.targets,
      originalFormData.value?.targets || [],
      isEqual,
    ).map((t) => pick(t, ["id", "config"]));

  loadingMap.isSubmitting = true;
  try {
    await ChatSyncData.patch(Number(route.params["id"]), {
      chatsync: formData.config,
      targets: targetsPayload,
    });
    toast.add({ color: "success", title: "消息同步配置已保存" });
    selectTarget.value = null;
    await refreshServerData();
  } catch (error) {
    toast.add({
      color: "error",
      description: fetchErrorMsg(error),
      title: "保存配置失败",
    });
  } finally {
    loadingMap.isSubmitting = false;
  }
};
type ChatSyncConfigOutput = z.output<typeof ChatSyncConfigSchema>;

const onFormSubmit = async (event: FormSubmitEvent<ChatSyncConfigOutput>) => {
  formData.config = event.data;
  await handleSubmit();
};

const cancelChanges = () => {
  if (originalFormData.value) {
    formData.config = structuredClone(toRaw(originalFormData.value.config));
    formData.targets = structuredClone(toRaw(originalFormData.value.targets));
  } else {
    formData.config = null;
    formData.targets = [];
  }
  selectTarget.value = null;
};

onMounted(async () => {
  await refreshServerData();
  setPageState({ isDirty: () => isDirty.value, save: handleSubmit });
});

onUnmounted(() => {
  clearPageState();
});
</script>
