// apps/web/src/pages/servers/notify.tsx
import { useParams } from "@tanstack/react-router";
import { differenceWith, isEqual, pick } from "lodash-es";
import { useEffect, useMemo, useState } from "react";
import type { z } from "zod";

import type { NotifyConfigSchema } from "#shared/model/server/schema/notify";
import type { targetResponse } from "#shared/model/server/schema/target";
import {
  renderDeathMessage,
  renderJoinMessage,
  renderLeaveMessage,
} from "#shared/utils/template/notify";
import { LoadingState } from "@/components/common/loading-state";
import {
  SettingsBlock,
  SettingsSection,
} from "@/components/common/settings-section";
import { ServerHeader } from "@/components/layout/server-header";
import { MessageTemplateField } from "@/components/target/message-template-field";
import { TargetConfigSheet } from "@/components/target/target-config-sheet";
import { Label } from "@/components/ui/label";
import { toast } from "@/components/ui/sonner";
import { Switch } from "@/components/ui/switch";
import { useRegisterPageState } from "@/hooks/use-page-state";
import { NotifyData } from "@/lib/api";
import { errorMessage } from "@/lib/http";
import { DEATH_MSG_VAR, PLAYER_NAME_VAR } from "@/lib/template-variables";
import { useServer } from "@/queries/servers";

type NotifyConfig = z.infer<typeof NotifyConfigSchema>;

// oxlint-disable-next-line eslint/complexity
export const ServerNotifyPage = () => {
  const { id } = useParams({ from: "/dashboard/servers/$id/notify" });
  const serverId = Number(id);

  const { data: server, refetch } = useServer(serverId);

  const [config, setConfig] = useState<NotifyConfig | null>(null);
  const [targets, setTargets] = useState<targetResponse[]>([]);
  const [original, setOriginal] = useState<{
    config: NotifyConfig;
    targets: targetResponse[];
  } | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);

  useEffect(() => {
    if (server) {
      setConfig(server.notifyConfig);
      setTargets(server.targets);
      setOriginal({
        config: structuredClone(server.notifyConfig),
        targets: structuredClone(server.targets),
      });
    }
  }, [server]);

  const isDirty = useMemo(
    () =>
      original !== null &&
      config !== null &&
      !isEqual({ config, targets }, original),
    [config, targets, original],
  );

  const handleSubmit = async (): Promise<void> => {
    if (!(original && config)) {
      return;
    }
    const changed = differenceWith(targets, original.targets, isEqual).map(
      (t) => pick(t, ["id", "config"]),
    );
    try {
      await NotifyData.patch(serverId, { notify: config, targets: changed });
      toast.success("配置已保存");
      setSelectedId(null);
      await refetch();
    } catch (error) {
      toast.error("保存配置失败", { description: errorMessage(error) });
    }
  };

  useRegisterPageState(
    isDirty,
    async () => handleSubmit(),
    () => {
      setConfig(structuredClone(original?.config ?? null));
      setTargets(structuredClone(original?.targets ?? []));
      setSelectedId(null);
    },
  );

  const selectedTarget = targets.find((t) => t.id === selectedId) ?? null;

  const updateTargetNotify = (
    patch: Partial<targetResponse["config"]["NotifyConfigSchema"]>,
  ): void => {
    if (!selectedTarget) {
      return;
    }
    setTargets((prev) =>
      prev.map((t) =>
        t.id === selectedTarget.id
          ? {
              ...t,
              config: {
                ...t.config,
                NotifyConfigSchema: {
                  ...t.config.NotifyConfigSchema,
                  ...patch,
                },
              },
            }
          : t,
      ),
    );
  };

  if (!(original && config)) {
    return (
      <>
        <ServerHeader />
        <div className="flex-1 overflow-y-auto p-6">
          <LoadingState />
        </div>
      </>
    );
  }

  return (
    <>
      <ServerHeader />
      <div className="scrollbar-custom flex-1 overflow-y-auto">
        <div className="mx-auto max-w-2xl px-4 py-8 lg:px-6">
          <div className="space-y-8">
            <SettingsSection
              description="玩家加入/离开服务器时发送通知"
              title="玩家进出事件"
            >
              <SettingsBlock>
                <MessageTemplateField
                  label="玩家进入时发送的消息"
                  onChange={(v) => {
                    setConfig({ ...config, join_notify_message: v });
                  }}
                  preview={renderJoinMessage(
                    config.join_notify_message,
                    "Steve",
                  )}
                  value={config.join_notify_message}
                  variables={[PLAYER_NAME_VAR]}
                />
              </SettingsBlock>
              <SettingsBlock>
                <MessageTemplateField
                  label="玩家离开时发送的消息"
                  onChange={(v) => {
                    setConfig({ ...config, leave_notify_message: v });
                  }}
                  preview={renderLeaveMessage(
                    config.leave_notify_message,
                    "Steve",
                  )}
                  value={config.leave_notify_message}
                  variables={[PLAYER_NAME_VAR]}
                />
              </SettingsBlock>
            </SettingsSection>

            <SettingsSection description="玩家死亡时发送通知" title="死亡事件">
              <SettingsBlock>
                <MessageTemplateField
                  label="玩家死亡时发送的消息"
                  onChange={(v) => {
                    setConfig({ ...config, death_notify_message: v });
                  }}
                  preview={renderDeathMessage(
                    config.death_notify_message,
                    "Steve",
                    "掉落",
                  )}
                  value={config.death_notify_message}
                  variables={[DEATH_MSG_VAR, PLAYER_NAME_VAR]}
                />
              </SettingsBlock>
            </SettingsSection>

            <SettingsSection
              description="针对不同目标单独配置通知开关"
              title="配置群聊"
            >
              <SettingsBlock>
                <TargetConfigSheet
                  onSelectedChange={setSelectedId}
                  selectedId={selectedId}
                  serverId={serverId}
                  targets={targets}
                >
                  {(target) => (
                    <div className="flex flex-col gap-4">
                      <div className="flex items-center justify-between">
                        <Label>玩家死亡通知</Label>
                        <Switch
                          checked={
                            target.config.NotifyConfigSchema
                              .player_disappoint_notify
                          }
                          onCheckedChange={(v) => {
                            updateTargetNotify({ player_disappoint_notify: v });
                          }}
                        />
                      </div>
                      <div className="flex items-center justify-between">
                        <Label>玩家进出通知</Label>
                        <Switch
                          checked={
                            target.config.NotifyConfigSchema.player_notify
                          }
                          onCheckedChange={(v) => {
                            updateTargetNotify({ player_notify: v });
                          }}
                        />
                      </div>
                    </div>
                  )}
                </TargetConfigSheet>
              </SettingsBlock>
            </SettingsSection>
          </div>
        </div>
      </div>
    </>
  );
};

// app/pages/servers/[id]/notify.vue
<template>
  <div class="h-full">
    <UDashboardPanel
      class="scrollbar-custom h-full"
      :ui="{ body: 'p-0 sm:p-0 overflow-y-auto overscroll-none' }"
    >
      <template #header>
        <ServerHeader />
      </template>
      <template #body>
        <UContainer class="py-8">
          <div class="mb-4" :class="isMobile ? 'columns-1' : 'columns-2'">
            <!-- 玩家进出事件 -->
            <UPageCard variant="outline" class="mb-4 break-inside-avoid">
              <template #title>玩家进出事件</template>
              <template #description>
                <span class="text-muted text-sm"
                  >玩家加入/离开服务器时发送通知</span
                >
              </template>
              <template #footer>
                <div class="flex flex-col gap-4">
                  <UFormField name="player_notify" label="是否启用">
                    <USwitch v-model="formData.config.player_notify" />
                  </UFormField>

                  <UFormField
                    name="join_notify_message"
                    label="玩家进出时发送的消息"
                  >
                    <UInput
                      v-model="formData.config.join_notify_message"
                      :maxlength="200"
                      class="w-full"
                      placeholder="玩家进入时的通知消息"
                    />
                    <div class="mt-2 space-y-2">
                      <p class="text-muted text-xs">点击变量插入到消息</p>
                      <div class="flex flex-wrap gap-1">
                        <UTooltip
                          v-for="tag in joinVariables"
                          :key="tag.value"
                          :text="`${tag.label} · [${tag.example}]`"
                        >
                          <UBadge
                            :color="
                              formData.config.join_notify_message.includes(
                                tag.value,
                              )
                                ? 'primary'
                                : 'neutral'
                            "
                            variant="subtle"
                            class="cursor-pointer"
                            @click="
                              insertPlaceholder(
                                'join_notify_message',
                                tag.value,
                              )
                            "
                          >
                            {{ tag.value }}
                          </UBadge>
                        </UTooltip>
                      </div>
                      <div class="text-muted text-sm">
                        预览：
                        <span class="text-success">{{
                          renderJoinMessage(
                            formData.config.join_notify_message,
                            "Steve",
                          )
                        }}</span>
                      </div>
                    </div>
                  </UFormField>

                  <UFormField
                    name="leave_notify_message"
                    label="玩家离开时发送的消息"
                  >
                    <UInput
                      v-model="formData.config.leave_notify_message"
                      :maxlength="200"
                      class="w-full"
                      placeholder="玩家离开时的通知消息"
                    />
                    <div class="mt-2 space-y-2">
                      <p class="text-muted text-xs">点击变量插入到消息</p>
                      <div class="flex flex-wrap gap-1">
                        <UTooltip
                          v-for="tag in leaveVariables"
                          :key="tag.value"
                          :text="`${tag.label} · [${tag.example}]`"
                        >
                          <UBadge
                            :color="
                              formData.config.leave_notify_message.includes(
                                tag.value,
                              )
                                ? 'primary'
                                : 'neutral'
                            "
                            variant="subtle"
                            class="cursor-pointer"
                            @click="
                              insertPlaceholder(
                                'leave_notify_message',
                                tag.value,
                              )
                            "
                          >
                            {{ tag.value }}
                          </UBadge>
                        </UTooltip>
                      </div>
                      <div class="text-muted text-sm">
                        预览：
                        <span class="text-success">{{
                          renderLeaveMessage(
                            formData.config.leave_notify_message,
                            "Steve",
                          )
                        }}</span>
                      </div>
                    </div>
                  </UFormField>
                </div>
              </template>
            </UPageCard>

            <!-- 死亡事件 -->
            <UPageCard variant="outline" class="mb-4 break-inside-avoid">
              <template #title>死亡事件</template>
              <template #description>
                <span class="text-muted text-sm">玩家死亡时发送通知</span>
              </template>
              <template #footer>
                <div class="flex flex-col gap-4">
                  <UFormField name="player_disappoint_notify" label="是否启用">
                    <USwitch
                      v-model="formData.config.player_disappoint_notify"
                    />
                  </UFormField>

                  <UFormField
                    name="death_notify_message"
                    label="玩家死亡时发送的消息"
                  >
                    <UInput
                      v-model="formData.config.death_notify_message"
                      :maxlength="200"
                      class="w-full"
                      placeholder="玩家死亡时的通知消息"
                    />
                    <div class="mt-2 space-y-2">
                      <p class="text-muted text-xs">点击变量插入到消息</p>
                      <div class="flex flex-wrap gap-1">
                        <UTooltip
                          v-for="tag in deathVariables"
                          :key="tag.value"
                          :text="`${tag.label} · [${tag.example}]`"
                        >
                          <UBadge
                            :color="
                              formData.config.death_notify_message.includes(
                                tag.value,
                              )
                                ? 'primary'
                                : 'neutral'
                            "
                            variant="subtle"
                            class="cursor-pointer"
                            @click="
                              insertPlaceholder(
                                'death_notify_message',
                                tag.value,
                              )
                            "
                          >
                            {{ tag.value }}
                          </UBadge>
                        </UTooltip>
                      </div>
                      <div class="text-muted text-sm">
                        预览：
                        <span class="text-success">{{
                          renderDeathMessage(
                            formData.config.death_notify_message,
                            "Steve",
                            "掉落",
                          )
                        }}</span>
                      </div>
                    </div>
                  </UFormField>
                </div>
              </template>
            </UPageCard>

            <!-- 配置群聊 -->
            <UPageCard variant="outline" class="mb-4 break-inside-avoid">
              <template #title>配置群聊</template>
              <template #description>
                <span class="text-muted text-sm">单独对目标进行配置</span>
              </template>
              <template #footer>
                <UDropdownMenu
                  v-if="options.length"
                  :items="
                    options.map((o) => ({
                      label: o.label,
                      onSelect: () => handleSelect(o.key),
                    }))
                  "
                >
                  <UButton icon="i-lucide-settings-2">配置目标</UButton>
                </UDropdownMenu>
                <UAlert
                  v-else
                  color="warning"
                  variant="subtle"
                  icon="i-lucide-triangle-alert"
                >
                  <template #description>
                    <UButton
                      variant="link"
                      color="warning"
                      size="sm"
                      class="p-0"
                      @click="router.push(`/servers/${route.params.id}/target`)"
                    >
                      你还没有创建目标哦（去创建）
                    </UButton>
                  </template>
                </UAlert>
              </template>
            </UPageCard>
          </div>

          <!-- 目标配置侧边栏 -->
          <USlideover
            v-model:open="drawerVisible"
            :title="
              selectTarget
                ? `目标配置 · ${selectTarget.targetId || selectTarget.id}`
                : ''
            "
          >
            <template #body>
              <div v-if="selectTarget">
                <UFormField label="是否开启此目标的通知" required>
                  <USwitch
                    v-model="selectTarget.config.NotifyConfigSchema.enabled"
                  />
                </UFormField>
              </div>
            </template>
          </USlideover>

          <USeparator class="my-4" />
          <div class="flex justify-end gap-2">
            <UButton
              color="neutral"
              variant="subtle"
              :disabled="!isDirty"
              :loading="isAnyLoading"
              @click="cancelChanges"
            >
              取消
            </UButton>
            <UButton
              :disabled="!isDirty"
              :loading="isAnyLoading"
              @click="handleSubmit"
            >
              保存设置
            </UButton>
          </div>
        </UContainer>
      </template>
    </UDashboardPanel>
  </div>
</template>

<script lang="ts" setup>
import { isEqual, differenceWith, pick } from "lodash-es";
import type { z } from "zod";
import { NotifyConfigSchema } from "~~/shared/schemas/server/notify";
import type { NotifyAPI } from "~~/shared/schemas/server/notify";
import type { ServerWithStatus } from "~~/shared/schemas/server/servers";
import type { targetResponse } from "~~/shared/schemas/server/target";
import { pickEditableTarget } from "~~/shared/utils/target";
import {
  renderDeathMessage,
  renderJoinMessage,
  renderLeaveMessage,
} from "~~/shared/utils/template/notify";

import ServerHeader from "@/components/header/server-header.vue";
import { useIsMobile } from "@/composables/is-mobile";
import { NotifyData, ServerData } from "~/composables/api";
import {
  createVariablesArray,
  createVariableMap,
} from "~/composables/use-placeholder-variables";

const isMobile = useIsMobile();

definePageMeta({ layout: "default" });

const { setPageState, clearPageState } = usePageStateStore();
const route = useRoute();
const toast = useToast();
const router = useRouter();

interface FormState {
  config: z.infer<typeof NotifyConfigSchema>;
  targets: targetResponse[];
}

const formData = reactive<FormState>({
  config: NotifyConfigSchema.parse({}),
  targets: [],
});

const selectTarget = ref<targetResponse | null>(null);
const drawerVisible = ref(false);
const originalFormData = ref<FormState | null>(null);
let serverData: ServerWithStatus | null = null;
const options = ref<{ label: string; key: string }[]>([]);

const loadingMap = reactive({
  isLoading: true,
  isSubmitting: false,
});

// 占位符变量定义
const NOTIFY_VARIABLES = createVariableMap({
  "{deathMessage}": { example: "掉落", label: "死亡原因" },
  "{playerName}": { example: "Steve", label: "玩家名称" },
});

const joinVariables = computed(() =>
  createVariablesArray({
    "{playerName}": NOTIFY_VARIABLES["{playerName}"],
  }),
);

const leaveVariables = computed(() =>
  createVariablesArray({
    "{playerName}": NOTIFY_VARIABLES["{playerName}"],
  }),
);

const deathVariables = computed(() =>
  createVariablesArray({
    "{deathMessage}": NOTIFY_VARIABLES["{deathMessage}"],
    "{playerName}": NOTIFY_VARIABLES["{playerName}"],
  }),
);

const insertPlaceholder = (
  field: keyof Pick<
    z.infer<typeof NotifyConfigSchema>,
    "join_notify_message" | "leave_notify_message" | "death_notify_message"
  >,
  placeholder: string,
) => {
  const current = formData.config[field] || "";
  formData.config[field] = current + placeholder;
};

const refreshServerData = async (): Promise<void> => {
  if (!route.params["id"]) {
    return;
  }
  loadingMap.isLoading = true;
  try {
    const data = await ServerData.get(Number(route.params["id"]));
    serverData = data;
    formData.config = structuredClone(data.notifyConfig);
    formData.targets = structuredClone(data.targets);
    originalFormData.value = structuredClone(toRaw(formData));
    options.value = data.targets.map((target) => ({
      key: target.id,
      label: target.targetId,
    }));
  } catch (error) {
    console.error(error);
    toast.add({ color: "error", title: "刷新服务器数据失败" });
  } finally {
    loadingMap.isLoading = false;
  }
};

const isDirty = computed(() => !isEqual(formData, originalFormData.value));

const isAnyLoading = computed(() => Object.values(loadingMap).some(Boolean));

const handleSelect = (key: string) => {
  drawerVisible.value = true;
  const selected = serverData?.targets.find((t) => t.id === key) || null;
  if (selected) {
    const editable = pickEditableTarget(selected, formData.targets);
    selectTarget.value = editable;
  }
};

const handleSubmit = async () => {
  if (!isDirty.value) {
    return;
  }

  const targetsPayload: z.infer<typeof NotifyAPI.PATCH.request>["targets"] =
    differenceWith(
      formData.targets,
      originalFormData.value?.targets || [],
      isEqual,
    ).map((t) => pick(t, ["id", "config"]));

  loadingMap.isSubmitting = true;
  try {
    await NotifyData.patch(Number(route.params["id"]), {
      notify: formData.config,
      targets: targetsPayload,
    });
    toast.add({ color: "success", title: "配置已保存" });
    selectTarget.value = null;
    await refreshServerData();
  } catch (error) {
    console.error("Submit failed:", error);
    toast.add({ color: "error", title: "保存配置失败，请稍后再试" });
  } finally {
    loadingMap.isSubmitting = false;
  }
};

const cancelChanges = () => {
  if (originalFormData.value) {
    Object.assign(formData, structuredClone(toRaw(originalFormData.value)));
  } else {
    formData.config = NotifyConfigSchema.parse({});
    formData.targets = [];
  }
  selectTarget.value = null;
};

onMounted(async () => {
  await refreshServerData();
  setPageState({ isDirty: () => isDirty.value, save: handleSubmit });
});

onUnmounted(() => {
  clearPageState();
});
</script>
